
<script src="<?= BASE_ASSET; ?>/js/jquery.hotkeys.js"></script>
<script type="text/javascript">
//This page is a result of an autogenerated content made by running test.html with firefox.
function domo(){
 
   // Binding keys
   $('*').bind('keydown', 'Ctrl+e', function assets() {
      $('#btn_edit').trigger('click');
       return false;
   });

   $('*').bind('keydown', 'Ctrl+x', function assets() {
      $('#btn_back').trigger('click');
       return false;
   });
    
}


jQuery(document).ready(domo);
</script>
<!-- Content Header (Page header) -->
<section class="content-header">
   <h1>
      Api Orders Products      <small><?= cclang('detail', ['Api Orders Products']); ?> </small>
   </h1>
   <ol class="breadcrumb">
      <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
      <li class=""><a  href="<?= site_url('administrator/api_orders_products'); ?>">Api Orders Products</a></li>
      <li class="active"><?= cclang('detail'); ?></li>
   </ol>
</section>
<!-- Main content -->
<section class="content">
   <div class="row" >
     
      <div class="col-md-12">
         <div class="box box-warning">
            <div class="box-body ">

               <!-- Widget: user widget style 1 -->
               <div class="box box-widget widget-user-2">
                  <!-- Add the bg color to the header using any of the bg-* classes -->
                  <div class="widget-user-header ">
                    
                     <div class="widget-user-image">
                        <img class="img-circle" src="<?= BASE_ASSET; ?>/img/view.png" alt="User Avatar">
                     </div>
                     <!-- /.widget-user-image -->
                     <h3 class="widget-user-username">Api Orders Products</h3>
                     <h5 class="widget-user-desc">Detail Api Orders Products</h5>
                     <hr>
                  </div>

                 
                  <div class="form-horizontal" name="form_api_orders_products" id="form_api_orders_products" >
                   
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Id </label>

                        <div class="col-sm-8">
                           <?= _ent($api_orders_products->id); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Item Id </label>

                        <div class="col-sm-8">
                           <?= _ent($api_orders_products->item_id); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Item Name </label>

                        <div class="col-sm-8">
                           <?= _ent($api_orders_products->item_name); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Item Type </label>

                        <div class="col-sm-8">
                           <?= _ent($api_orders_products->item_type); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Item Data </label>

                        <div class="col-sm-8">
                           <?= _ent($api_orders_products->item_data); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Variation Id </label>

                        <div class="col-sm-8">
                           <?= _ent($api_orders_products->variation_id); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Quantity </label>

                        <div class="col-sm-8">
                           <?= _ent($api_orders_products->quantity); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Tax Class </label>

                        <div class="col-sm-8">
                           <?= _ent($api_orders_products->tax_class); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Line Subtotal </label>

                        <div class="col-sm-8">
                           <?= _ent($api_orders_products->line_subtotal); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Line Subtotal Tax </label>

                        <div class="col-sm-8">
                           <?= _ent($api_orders_products->line_subtotal_tax); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Line Total </label>

                        <div class="col-sm-8">
                           <?= _ent($api_orders_products->line_total); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Line Total Tax </label>

                        <div class="col-sm-8">
                           <?= _ent($api_orders_products->line_total_tax); ?>
                        </div>
                    </div>
                                        
                    <br>
                    <br>

                    <div class="view-nav">
                        <?php is_allowed('api_orders_products_update', function() use ($api_orders_products){?>
                        <a class="btn btn-flat btn-info btn_edit btn_action" id="btn_edit" data-stype='back' title="edit api_orders_products (Ctrl+e)" href="<?= site_url('administrator/api_orders_products/edit/'.$api_orders_products->id); ?>"><i class="fa fa-edit" ></i> <?= cclang('update', ['Api Orders Products']); ?> </a>
                        <?php }) ?>
                        <a class="btn btn-flat btn-default btn_action" id="btn_back" title="back (Ctrl+x)" href="<?= site_url('administrator/api_orders_products/'); ?>"><i class="fa fa-undo" ></i> <?= cclang('go_list_button', ['Api Orders Products']); ?></a>
                     </div>
                    
                  </div>
               </div>
            </div>
            <!--/box body -->
         </div>
         <!--/box -->

      </div>
   </div>
</section>
<!-- /.content -->
