
<script src="<?= BASE_ASSET; ?>/js/jquery.hotkeys.js"></script>
<script type="text/javascript">
//This page is a result of an autogenerated content made by running test.html with firefox.
function domo(){
 
   // Binding keys
   $('*').bind('keydown', 'Ctrl+e', function assets() {
      $('#btn_edit').trigger('click');
       return false;
   });

   $('*').bind('keydown', 'Ctrl+x', function assets() {
      $('#btn_back').trigger('click');
       return false;
   });
    
}


jQuery(document).ready(domo);
</script>
<!-- Content Header (Page header) -->
<section class="content-header">
   <h1>
      Site Orders      <small><?= cclang('detail', ['Site Orders']); ?> </small>
   </h1>
   <ol class="breadcrumb">
      <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
      <li class=""><a  href="<?= site_url('administrator/site_orders'); ?>">Site Orders</a></li>
      <li class="active"><?= cclang('detail'); ?></li>
   </ol>
</section>
<!-- Main content -->
<section class="content">
   <div class="row" >
     
      <div class="col-md-12">
         <div class="box box-warning">
            <div class="box-body ">

               <!-- Widget: user widget style 1 -->
               <div class="box box-widget widget-user-2">
                  <!-- Add the bg color to the header using any of the bg-* classes -->
                  <div class="widget-user-header ">
                    
                     <div class="widget-user-image">
                        <img class="img-circle" src="<?= BASE_ASSET; ?>/img/view.png" alt="User Avatar">
                     </div>
                     <!-- /.widget-user-image -->
                     <h3 class="widget-user-username">Site Orders</h3>
                     <h5 class="widget-user-desc">Detail Site Orders</h5>
                     <hr>
                  </div>

                 
                  <div class="form-horizontal" name="form_site_orders" id="form_site_orders" >
                   
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Id </label>

                        <div class="col-sm-8">
                           <?= _ent($site_orders->id); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">PostID </label>

                        <div class="col-sm-8">
                           <?= _ent($site_orders->PostID); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">WaybillNo </label>

                        <div class="col-sm-8">
                           <?= _ent($site_orders->WaybillNo); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">SendAccNo </label>

                        <div class="col-sm-8">
                           <?= _ent($site_orders->SendAccNo); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">SendSite </label>

                        <div class="col-sm-8">
                           <?= _ent($site_orders->SendSite); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">SendCompany </label>

                        <div class="col-sm-8">
                           <?= _ent($site_orders->SendCompany); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">SendAdd1 </label>

                        <div class="col-sm-8">
                           <?= _ent($site_orders->SendAdd1); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">SendAdd2 </label>

                        <div class="col-sm-8">
                           <?= _ent($site_orders->SendAdd2); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">SendAdd3 </label>

                        <div class="col-sm-8">
                           <?= _ent($site_orders->SendAdd3); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">SendAdd4 </label>

                        <div class="col-sm-8">
                           <?= _ent($site_orders->SendAdd4); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">SendAdd5 </label>

                        <div class="col-sm-8">
                           <?= _ent($site_orders->SendAdd5); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">SendContactPerson </label>

                        <div class="col-sm-8">
                           <?= _ent($site_orders->SendContactPerson); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">SendHomeTel </label>

                        <div class="col-sm-8">
                           <?= _ent($site_orders->SendHomeTel); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">SendWorkTel </label>

                        <div class="col-sm-8">
                           <?= _ent($site_orders->SendWorkTel); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">SendCell </label>

                        <div class="col-sm-8">
                           <?= _ent($site_orders->SendCell); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">RecCompany </label>

                        <div class="col-sm-8">
                           <?= _ent($site_orders->RecCompany); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">RecAdd1 </label>

                        <div class="col-sm-8">
                           <?= _ent($site_orders->RecAdd1); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">RecAdd2 </label>

                        <div class="col-sm-8">
                           <?= _ent($site_orders->RecAdd2); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">RecAdd3 </label>

                        <div class="col-sm-8">
                           <?= _ent($site_orders->RecAdd3); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">RecAdd4 </label>

                        <div class="col-sm-8">
                           <?= _ent($site_orders->RecAdd4); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">RecAdd5 </label>

                        <div class="col-sm-8">
                           <?= _ent($site_orders->RecAdd5); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">RecContactPerson </label>

                        <div class="col-sm-8">
                           <?= _ent($site_orders->RecContactPerson); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">RecHomeTel </label>

                        <div class="col-sm-8">
                           <?= _ent($site_orders->RecHomeTel); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">RecWorkTel </label>

                        <div class="col-sm-8">
                           <?= _ent($site_orders->RecWorkTel); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">RecCell </label>

                        <div class="col-sm-8">
                           <?= _ent($site_orders->RecCell); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">SpecialInstructions </label>

                        <div class="col-sm-8">
                           <?= _ent($site_orders->SpecialInstructions); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">ServiceType </label>

                        <div class="col-sm-8">
                           <?= _ent($site_orders->ServiceType); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">TotQTY </label>

                        <div class="col-sm-8">
                           <?= _ent($site_orders->TotQTY); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">TotMass </label>

                        <div class="col-sm-8">
                           <?= _ent($site_orders->TotMass); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Insurance </label>

                        <div class="col-sm-8">
                           <?= _ent($site_orders->Insurance); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">InsuranceValue </label>

                        <div class="col-sm-8">
                           <?= _ent($site_orders->InsuranceValue); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">CustomerRef </label>

                        <div class="col-sm-8">
                           <?= _ent($site_orders->CustomerRef); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">StoreCode </label>

                        <div class="col-sm-8">
                           <?= _ent($site_orders->StoreCode); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">SecurityStamp </label>

                        <div class="col-sm-8">
                           <?= _ent($site_orders->SecurityStamp); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">RequiredDocs </label>

                        <div class="col-sm-8">
                           <?= _ent($site_orders->RequiredDocs); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">WaybillInstructions </label>

                        <div class="col-sm-8">
                           <?= _ent($site_orders->WaybillInstructions); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">InstructionCode </label>

                        <div class="col-sm-8">
                           <?= _ent($site_orders->InstructionCode); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">IsSecureDelivery </label>

                        <div class="col-sm-8">
                           <?= _ent($site_orders->IsSecureDelivery); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">VerificationNumbers </label>

                        <div class="col-sm-8">
                           <?= _ent($site_orders->VerificationNumbers); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">GenerateSecurePin </label>

                        <div class="col-sm-8">
                           <?= _ent($site_orders->GenerateSecurePin); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">CollectionNo </label>

                        <div class="col-sm-8">
                           <?= _ent($site_orders->CollectionNo); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">InvoiceRef </label>

                        <div class="col-sm-8">
                           <?= _ent($site_orders->invoiceRef); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">CompleteWaybillAfterSave </label>

                        <div class="col-sm-8">
                           <?= _ent($site_orders->CompleteWaybillAfterSave); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">ParcelsWaybillNo </label>

                        <div class="col-sm-8">
                           <?= _ent($site_orders->ParcelsWaybillNo); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">ParcelsLength </label>

                        <div class="col-sm-8">
                           <?= _ent($site_orders->ParcelsLength); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">ParcelsHeight </label>

                        <div class="col-sm-8">
                           <?= _ent($site_orders->ParcelsHeight); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">ParcelsWidth </label>

                        <div class="col-sm-8">
                           <?= _ent($site_orders->ParcelsWidth); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">ParcelsMass </label>

                        <div class="col-sm-8">
                           <?= _ent($site_orders->ParcelsMass); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">ParcelDescription </label>

                        <div class="col-sm-8">
                           <?= _ent($site_orders->ParcelDescription); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">ParcelNo </label>

                        <div class="col-sm-8">
                           <?= _ent($site_orders->ParcelNo); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">ParcelCount </label>

                        <div class="col-sm-8">
                           <?= _ent($site_orders->ParcelCount); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">OrderStatus </label>

                        <div class="col-sm-8">
                           <?= _ent($site_orders->OrderStatus); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">OrderDiscountTotal </label>

                        <div class="col-sm-8">
                           <?= _ent($site_orders->OrderDiscountTotal); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">OrderDiscountTax </label>

                        <div class="col-sm-8">
                           <?= _ent($site_orders->OrderDiscountTax); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">OrderShippingTotal </label>

                        <div class="col-sm-8">
                           <?= _ent($site_orders->OrderShippingTotal); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">OrderShippingTax </label>

                        <div class="col-sm-8">
                           <?= _ent($site_orders->OrderShippingTax); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">OrderTotal </label>

                        <div class="col-sm-8">
                           <?= _ent($site_orders->OrderTotal); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">OrderTotalTax </label>

                        <div class="col-sm-8">
                           <?= _ent($site_orders->OrderTotalTax); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">OrderPaymentMethod </label>

                        <div class="col-sm-8">
                           <?= _ent($site_orders->OrderPaymentMethod); ?>
                        </div>
                    </div>
                                        
                    <br>
                    <br>

                    <div class="view-nav">
                        <?php is_allowed('site_orders_update', function() use ($site_orders){?>
                        <a class="btn btn-flat btn-info btn_edit btn_action" id="btn_edit" data-stype='back' title="edit site_orders (Ctrl+e)" href="<?= site_url('administrator/site_orders/edit/'.$site_orders->WaybillNo); ?>"><i class="fa fa-edit" ></i> <?= cclang('update', ['Site Orders']); ?> </a>
                        <?php }) ?>
                        <a class="btn btn-flat btn-default btn_action" id="btn_back" title="back (Ctrl+x)" href="<?= site_url('administrator/site_orders/'); ?>"><i class="fa fa-undo" ></i> <?= cclang('go_list_button', ['Site Orders']); ?></a>
                     </div>
                    
                  </div>
               </div>
            </div>
            <!--/box body -->
         </div>
         <!--/box -->

      </div>
   </div>
</section>
<!-- /.content -->
