
<script src="<?= BASE_ASSET; ?>/js/jquery.hotkeys.js"></script>

<script type="text/javascript">
//This page is a result of an autogenerated content made by running test.html with firefox.
function domo(){
 
   // Binding keys
   $('*').bind('keydown', 'Ctrl+a', function assets() {
       window.location.href = BASE_URL + '/administrator/Dawnwingapi/add';
       return false;
   });

   $('*').bind('keydown', 'Ctrl+f', function assets() {
       $('#sbtn').trigger('click');
       return false;
   });

   $('*').bind('keydown', 'Ctrl+x', function assets() {
       $('#reset').trigger('click');
       return false;
   });

   $('*').bind('keydown', 'Ctrl+b', function assets() {

       $('#reset').trigger('click');
       return false;
   });
}

jQuery(document).ready(domo);
</script>
<!-- Content Header (Page header) -->
<section class="content-header">
   <h1>
      <?= cclang('dawnwingapi') ?><small><?= cclang('list_all'); ?></small>
   </h1>
   <ol class="breadcrumb">
      <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
      <li class="active"><?= cclang('dawnwingapi') ?></li>
   </ol>
</section>
<!-- Main content -->
<section class="content">
   <div class="row" >
      
      <div class="col-md-12">
         <div class="box box-warning">
            <div class="box-body ">
               <!-- Widget: user widget style 1 -->
               <div class="box box-widget widget-user-2">
                  <!-- Add the bg color to the header using any of the bg-* classes -->
                  <div class="widget-user-header ">
                     <div class="row pull-right">
                        <?php is_allowed('dawnwingapi_add', function(){?>
                        <a class="btn btn-flat btn-success btn_add_new" id="btn_add_new" title="<?= cclang('add_new_button', [cclang('dawnwingapi')]); ?>  (Ctrl+a)" href="<?=  site_url('administrator/dawnwingapi/add'); ?>"><i class="fa fa-plus-square-o" ></i> <?= cclang('add_new_button', [cclang('dawnwingapi')]); ?></a>
                        <?php }) ?>
                        <?php is_allowed('dawnwingapi_export', function(){?>
                        <a class="btn btn-flat btn-success" title="<?= cclang('export'); ?> <?= cclang('dawnwingapi') ?>']); ?>" href="<?= site_url('administrator/dawnwingapi/export'); ?>"><i class="fa fa-file-excel-o" ></i> <?= cclang('export'); ?> XLS</a>
                        <?php }) ?>
                        <?php is_allowed('dawnwingapi_export', function(){?>
                        <a class="btn btn-flat btn-success" title="<?= cclang('export'); ?> pdf <?= cclang('dawnwingapi') ?>']); ?>" href="<?= site_url('administrator/dawnwingapi/export_pdf'); ?>"><i class="fa fa-file-pdf-o" ></i> <?= cclang('export'); ?> PDF</a>
                        <?php }) ?>
                     </div>
                     <div class="widget-user-image">
                        <img class="img-circle" src="<?= BASE_ASSET; ?>/img/list.png" alt="User Avatar">
                     </div>
                     <!-- /.widget-user-image -->
                     <h3 class="widget-user-username"><?= cclang('dawnwingapi') ?></h3>
                     <h5 class="widget-user-desc"><?= cclang('list_all', [cclang('dawnwingapi')]); ?>  <i class="label bg-yellow"><?= $dawnwingapi_counts; ?>  <?= cclang('items'); ?></i></h5>
                  </div>

                  <form name="form_dawnwingapi" id="form_dawnwingapi" action="<?= base_url('administrator/dawnwingapi/index'); ?>">
                  

                  <div class="table-responsive"> 
                  <table class="table table-bordered table-striped dataTable">
                     <thead>
                        <tr class="">
                                                     <th>
                            <input type="checkbox" class="flat-red toltip" id="check_all" name="check_all" title="check all">
                           </th>
                                                    <th> <?= cclang('id') ?></th>
                           <th> <?= cclang('PostID') ?></th>
                           <th> <?= cclang('SendAccNo') ?></th>
                           <th> <?= cclang('SendSite') ?></th>
                           <th> <?= cclang('SendCompany') ?></th>
                           <th> <?= cclang('SendAdd1') ?></th>
                           <th> <?= cclang('SendAdd2') ?></th>
                           <th> <?= cclang('SendAdd3') ?></th>
                           <th> <?= cclang('SendAdd4') ?></th>
                           <th> <?= cclang('SendAdd5') ?></th>
                           <th> <?= cclang('SendContactPerson') ?></th>
                           <th> <?= cclang('SendHomeTel') ?></th>
                           <th> <?= cclang('SendWorkTel') ?></th>
                           <th> <?= cclang('SendCell') ?></th>
                           <th> <?= cclang('RecCompany') ?></th>
                           <th> <?= cclang('RecAdd1') ?></th>
                           <th> <?= cclang('RecAdd2') ?></th>
                           <th> <?= cclang('RecAdd3') ?></th>
                           <th> <?= cclang('RecAdd4') ?></th>
                           <th> <?= cclang('RecAdd5') ?></th>
                           <th> <?= cclang('RecAdd6') ?></th>
                           <th> <?= cclang('RecAdd7') ?></th>
                           <th> <?= cclang('RecContactPerson') ?></th>
                           <th> <?= cclang('RecHomeTel') ?></th>
                           <th> <?= cclang('RecWorkTel') ?></th>
                           <th> <?= cclang('RecCell') ?></th>
                           <th> <?= cclang('SpecialInstructions') ?></th>
                           <th> <?= cclang('ServiceType') ?></th>
                           <th> <?= cclang('TotQTY') ?></th>
                           <th> <?= cclang('TotMass') ?></th>
                           <th> <?= cclang('Insurance') ?></th>
                           <th> <?= cclang('InsuranceValue') ?></th>
                           <th> <?= cclang('CustomerRef') ?></th>
                           <th> <?= cclang('StoreCode') ?></th>
                           <th> <?= cclang('SecurityStamp') ?></th>
                           <th> <?= cclang('RequiredDocs') ?></th>
                           <th> <?= cclang('WaybillInstructions') ?></th>
                           <th> <?= cclang('InstructionCode') ?></th>
                           <th> <?= cclang('IsSecureDelivery') ?></th>
                           <th> <?= cclang('VerificationNumbers') ?></th>
                           <th> <?= cclang('GenerateSecurePin') ?></th>
                           <th> <?= cclang('CollectionNo') ?></th>
                           <th> <?= cclang('invoiceRef') ?></th>
                           <th> <?= cclang('CompleteWaybillAfterSave') ?></th>
                           <th> <?= cclang('ParcelsWaybillNo') ?></th>
                           <th> <?= cclang('ParcelsLength') ?></th>
                           <th> <?= cclang('ParcelsHeight') ?></th>
                           <th> <?= cclang('ParcelsWidth') ?></th>
                           <th> <?= cclang('ParcelsMass') ?></th>
                           <th> <?= cclang('ParcelDescription') ?></th>
                           <th> <?= cclang('ParcelNo') ?></th>
                           <th> <?= cclang('ParcelCount') ?></th>
                           <th> <?= cclang('OrderStatus') ?></th>
                           <th> <?= cclang('OrderDiscountTotal') ?></th>
                           <th> <?= cclang('OrderDiscountTax') ?></th>
                           <th> <?= cclang('OrderShippingTotal') ?></th>
                           <th> <?= cclang('OrderShippingTax') ?></th>
                           <th> <?= cclang('OrderTotal') ?></th>
                           <th>Action</th>                        </tr>
                     </thead>
                     <tbody id="tbody_dawnwingapi">
                     <?php foreach($dawnwingapis as $dawnwingapi): ?>
                        <tr>
                                                       <td width="5">
                              <input type="checkbox" class="flat-red check" name="id[]" value="<?= $dawnwingapi->WaybillNo; ?>">
                           </td>
                                                       
                           <td><?= _ent($dawnwingapi->id); ?></td> 
                           <td><?= _ent($dawnwingapi->PostID); ?></td> 
                           <td><?= _ent($dawnwingapi->SendAccNo); ?></td> 
                           <td><?= _ent($dawnwingapi->SendSite); ?></td> 
                           <td><?= _ent($dawnwingapi->SendCompany); ?></td> 
                           <td><?= _ent($dawnwingapi->SendAdd1); ?></td> 
                           <td><?= _ent($dawnwingapi->SendAdd2); ?></td> 
                           <td><?= _ent($dawnwingapi->SendAdd3); ?></td> 
                           <td><?= _ent($dawnwingapi->SendAdd4); ?></td> 
                           <td><?= _ent($dawnwingapi->SendAdd5); ?></td> 
                           <td><?= _ent($dawnwingapi->SendContactPerson); ?></td> 
                           <td><?= _ent($dawnwingapi->SendHomeTel); ?></td> 
                           <td><?= _ent($dawnwingapi->SendWorkTel); ?></td> 
                           <td><?= _ent($dawnwingapi->SendCell); ?></td> 
                           <td><?= _ent($dawnwingapi->RecCompany); ?></td> 
                           <td><?= _ent($dawnwingapi->RecAdd1); ?></td> 
                           <td><?= _ent($dawnwingapi->RecAdd2); ?></td> 
                           <td><?= _ent($dawnwingapi->RecAdd3); ?></td> 
                           <td><?= _ent($dawnwingapi->RecAdd4); ?></td> 
                           <td><?= _ent($dawnwingapi->RecAdd5); ?></td> 
                           <td><?= _ent($dawnwingapi->RecAdd6); ?></td> 
                           <td><?= _ent($dawnwingapi->RecAdd7); ?></td> 
                           <td><?= _ent($dawnwingapi->RecContactPerson); ?></td> 
                           <td><?= _ent($dawnwingapi->RecHomeTel); ?></td> 
                           <td><?= _ent($dawnwingapi->RecWorkTel); ?></td> 
                           <td><?= _ent($dawnwingapi->RecCell); ?></td> 
                           <td><?= _ent($dawnwingapi->SpecialInstructions); ?></td> 
                           <td><?= _ent($dawnwingapi->ServiceType); ?></td> 
                           <td><?= _ent($dawnwingapi->TotQTY); ?></td> 
                           <td><?= _ent($dawnwingapi->TotMass); ?></td> 
                           <td><?= _ent($dawnwingapi->Insurance); ?></td> 
                           <td><?= _ent($dawnwingapi->InsuranceValue); ?></td> 
                           <td><?= _ent($dawnwingapi->CustomerRef); ?></td> 
                           <td><?= _ent($dawnwingapi->StoreCode); ?></td> 
                           <td><?= _ent($dawnwingapi->SecurityStamp); ?></td> 
                           <td><?= _ent($dawnwingapi->RequiredDocs); ?></td> 
                           <td><?= _ent($dawnwingapi->WaybillInstructions); ?></td> 
                           <td><?= _ent($dawnwingapi->InstructionCode); ?></td> 
                           <td><?= _ent($dawnwingapi->IsSecureDelivery); ?></td> 
                           <td><?= _ent($dawnwingapi->VerificationNumbers); ?></td> 
                           <td><?= _ent($dawnwingapi->GenerateSecurePin); ?></td> 
                           <td><?= _ent($dawnwingapi->CollectionNo); ?></td> 
                           <td><?= _ent($dawnwingapi->invoiceRef); ?></td> 
                           <td><?= _ent($dawnwingapi->CompleteWaybillAfterSave); ?></td> 
                           <td><?= _ent($dawnwingapi->ParcelsWaybillNo); ?></td> 
                           <td><?= _ent($dawnwingapi->ParcelsLength); ?></td> 
                           <td><?= _ent($dawnwingapi->ParcelsHeight); ?></td> 
                           <td><?= _ent($dawnwingapi->ParcelsWidth); ?></td> 
                           <td><?= _ent($dawnwingapi->ParcelsMass); ?></td> 
                           <td><?= _ent($dawnwingapi->ParcelDescription); ?></td> 
                           <td><?= _ent($dawnwingapi->ParcelNo); ?></td> 
                           <td><?= _ent($dawnwingapi->ParcelCount); ?></td> 
                           <td><?= _ent($dawnwingapi->OrderStatus); ?></td> 
                           <td><?= _ent($dawnwingapi->OrderDiscountTotal); ?></td> 
                           <td><?= _ent($dawnwingapi->OrderDiscountTax); ?></td> 
                           <td><?= _ent($dawnwingapi->OrderShippingTotal); ?></td> 
                           <td><?= _ent($dawnwingapi->OrderShippingTax); ?></td> 
                           <td><?= _ent($dawnwingapi->OrderTotal); ?></td> 
                           <td width="200">
                            
                                                              <?php is_allowed('dawnwingapi_view', function() use ($dawnwingapi){?>
                                 <a href="<?= site_url('administrator/dawnwingapi/single_pdf/' .$dawnwingapi->WaybillNo); ?>" class="label-default"><i class="fa fa-file-pdf-o"></i> <?= cclang('PDF') ?>
                              <a href="<?= site_url('administrator/dawnwingapi/view/' . $dawnwingapi->WaybillNo); ?>" class="label-default"><i class="fa fa-newspaper-o"></i> <?= cclang('view_button'); ?>
                              <?php }) ?>
                              <?php is_allowed('dawnwingapi_update', function() use ($dawnwingapi){?>
                              <a href="<?= site_url('administrator/dawnwingapi/edit/' . $dawnwingapi->WaybillNo); ?>" class="label-default"><i class="fa fa-edit "></i> <?= cclang('update_button'); ?></a>
                              <?php }) ?>
                              <?php is_allowed('dawnwingapi_delete', function() use ($dawnwingapi){?>
                              <a href="javascript:void(0);" data-href="<?= site_url('administrator/dawnwingapi/delete/' . $dawnwingapi->WaybillNo); ?>" class="label-default remove-data"><i class="fa fa-close"></i> <?= cclang('remove_button'); ?></a>
                               <?php }) ?>

                           </td>                        </tr>
                      <?php endforeach; ?>
                      <?php if ($dawnwingapi_counts == 0) :?>
                         <tr>
                           <td colspan="100">
                           Dawnwingapi data is not available
                           </td>
                         </tr>
                      <?php endif; ?>
                     </tbody>
                  </table>
                  </div>
               </div>
               <hr>
               <!-- /.widget-user -->
               <div class="row">
                  <div class="col-md-8">
                     <div class="col-sm-2 padd-left-0 " >
                        <select type="text" class="form-control chosen chosen-select" name="bulk" id="bulk" placeholder="Site Email" >
                           <option value="">Bulk</option>
                                                     <option value="delete">Delete</option>
                                                  </select>
                     </div>
                     <div class="col-sm-2 padd-left-0 ">
                        <button type="button" class="btn btn-flat" name="apply" id="apply" title="<?= cclang('apply_bulk_action'); ?>"><?= cclang('apply_button'); ?></button>
                     </div>
                     <div class="col-sm-3 padd-left-0  " >
                        <input type="text" class="form-control" name="q" id="filter" placeholder="<?= cclang('filter'); ?>" value="<?= $this->input->get('q'); ?>">
                     </div>
                     <div class="col-sm-3 padd-left-0 " >
                        <select type="text" class="form-control chosen chosen-select" name="f" id="field" >
                           <option value=""><?= cclang('all'); ?></option>
                            <option <?= $this->input->get('f') == 'id' ? 'selected' :''; ?> value="id">Id</option>
                           <option <?= $this->input->get('f') == 'PostID' ? 'selected' :''; ?> value="PostID">PostID</option>
                           <option <?= $this->input->get('f') == 'SendAccNo' ? 'selected' :''; ?> value="SendAccNo">SendAccNo</option>
                           <option <?= $this->input->get('f') == 'SendSite' ? 'selected' :''; ?> value="SendSite">SendSite</option>
                           <option <?= $this->input->get('f') == 'SendCompany' ? 'selected' :''; ?> value="SendCompany">SendCompany</option>
                           <option <?= $this->input->get('f') == 'SendAdd1' ? 'selected' :''; ?> value="SendAdd1">SendAdd1</option>
                           <option <?= $this->input->get('f') == 'SendAdd2' ? 'selected' :''; ?> value="SendAdd2">SendAdd2</option>
                           <option <?= $this->input->get('f') == 'SendAdd3' ? 'selected' :''; ?> value="SendAdd3">SendAdd3</option>
                           <option <?= $this->input->get('f') == 'SendAdd4' ? 'selected' :''; ?> value="SendAdd4">SendAdd4</option>
                           <option <?= $this->input->get('f') == 'SendAdd5' ? 'selected' :''; ?> value="SendAdd5">SendAdd5</option>
                           <option <?= $this->input->get('f') == 'SendContactPerson' ? 'selected' :''; ?> value="SendContactPerson">SendContactPerson</option>
                           <option <?= $this->input->get('f') == 'SendHomeTel' ? 'selected' :''; ?> value="SendHomeTel">SendHomeTel</option>
                           <option <?= $this->input->get('f') == 'SendWorkTel' ? 'selected' :''; ?> value="SendWorkTel">SendWorkTel</option>
                           <option <?= $this->input->get('f') == 'SendCell' ? 'selected' :''; ?> value="SendCell">SendCell</option>
                           <option <?= $this->input->get('f') == 'RecCompany' ? 'selected' :''; ?> value="RecCompany">RecCompany</option>
                           <option <?= $this->input->get('f') == 'RecAdd1' ? 'selected' :''; ?> value="RecAdd1">RecAdd1</option>
                           <option <?= $this->input->get('f') == 'RecAdd2' ? 'selected' :''; ?> value="RecAdd2">RecAdd2</option>
                           <option <?= $this->input->get('f') == 'RecAdd3' ? 'selected' :''; ?> value="RecAdd3">RecAdd3</option>
                           <option <?= $this->input->get('f') == 'RecAdd4' ? 'selected' :''; ?> value="RecAdd4">RecAdd4</option>
                           <option <?= $this->input->get('f') == 'RecAdd5' ? 'selected' :''; ?> value="RecAdd5">RecAdd5</option>
                           <option <?= $this->input->get('f') == 'RecAdd6' ? 'selected' :''; ?> value="RecAdd6">RecAdd6</option>
                           <option <?= $this->input->get('f') == 'RecAdd7' ? 'selected' :''; ?> value="RecAdd7">RecAdd7</option>
                           <option <?= $this->input->get('f') == 'RecContactPerson' ? 'selected' :''; ?> value="RecContactPerson">RecContactPerson</option>
                           <option <?= $this->input->get('f') == 'RecHomeTel' ? 'selected' :''; ?> value="RecHomeTel">RecHomeTel</option>
                           <option <?= $this->input->get('f') == 'RecWorkTel' ? 'selected' :''; ?> value="RecWorkTel">RecWorkTel</option>
                           <option <?= $this->input->get('f') == 'RecCell' ? 'selected' :''; ?> value="RecCell">RecCell</option>
                           <option <?= $this->input->get('f') == 'SpecialInstructions' ? 'selected' :''; ?> value="SpecialInstructions">SpecialInstructions</option>
                           <option <?= $this->input->get('f') == 'ServiceType' ? 'selected' :''; ?> value="ServiceType">ServiceType</option>
                           <option <?= $this->input->get('f') == 'TotQTY' ? 'selected' :''; ?> value="TotQTY">TotQTY</option>
                           <option <?= $this->input->get('f') == 'TotMass' ? 'selected' :''; ?> value="TotMass">TotMass</option>
                           <option <?= $this->input->get('f') == 'Insurance' ? 'selected' :''; ?> value="Insurance">Insurance</option>
                           <option <?= $this->input->get('f') == 'InsuranceValue' ? 'selected' :''; ?> value="InsuranceValue">InsuranceValue</option>
                           <option <?= $this->input->get('f') == 'CustomerRef' ? 'selected' :''; ?> value="CustomerRef">CustomerRef</option>
                           <option <?= $this->input->get('f') == 'StoreCode' ? 'selected' :''; ?> value="StoreCode">StoreCode</option>
                           <option <?= $this->input->get('f') == 'SecurityStamp' ? 'selected' :''; ?> value="SecurityStamp">SecurityStamp</option>
                           <option <?= $this->input->get('f') == 'RequiredDocs' ? 'selected' :''; ?> value="RequiredDocs">RequiredDocs</option>
                           <option <?= $this->input->get('f') == 'WaybillInstructions' ? 'selected' :''; ?> value="WaybillInstructions">WaybillInstructions</option>
                           <option <?= $this->input->get('f') == 'InstructionCode' ? 'selected' :''; ?> value="InstructionCode">InstructionCode</option>
                           <option <?= $this->input->get('f') == 'IsSecureDelivery' ? 'selected' :''; ?> value="IsSecureDelivery">IsSecureDelivery</option>
                           <option <?= $this->input->get('f') == 'VerificationNumbers' ? 'selected' :''; ?> value="VerificationNumbers">VerificationNumbers</option>
                           <option <?= $this->input->get('f') == 'GenerateSecurePin' ? 'selected' :''; ?> value="GenerateSecurePin">GenerateSecurePin</option>
                           <option <?= $this->input->get('f') == 'CollectionNo' ? 'selected' :''; ?> value="CollectionNo">CollectionNo</option>
                           <option <?= $this->input->get('f') == 'invoiceRef' ? 'selected' :''; ?> value="invoiceRef">InvoiceRef</option>
                           <option <?= $this->input->get('f') == 'CompleteWaybillAfterSave' ? 'selected' :''; ?> value="CompleteWaybillAfterSave">CompleteWaybillAfterSave</option>
                           <option <?= $this->input->get('f') == 'ParcelsWaybillNo' ? 'selected' :''; ?> value="ParcelsWaybillNo">ParcelsWaybillNo</option>
                           <option <?= $this->input->get('f') == 'ParcelsLength' ? 'selected' :''; ?> value="ParcelsLength">ParcelsLength</option>
                           <option <?= $this->input->get('f') == 'ParcelsHeight' ? 'selected' :''; ?> value="ParcelsHeight">ParcelsHeight</option>
                           <option <?= $this->input->get('f') == 'ParcelsWidth' ? 'selected' :''; ?> value="ParcelsWidth">ParcelsWidth</option>
                           <option <?= $this->input->get('f') == 'ParcelsMass' ? 'selected' :''; ?> value="ParcelsMass">ParcelsMass</option>
                           <option <?= $this->input->get('f') == 'ParcelDescription' ? 'selected' :''; ?> value="ParcelDescription">ParcelDescription</option>
                           <option <?= $this->input->get('f') == 'ParcelNo' ? 'selected' :''; ?> value="ParcelNo">ParcelNo</option>
                           <option <?= $this->input->get('f') == 'ParcelCount' ? 'selected' :''; ?> value="ParcelCount">ParcelCount</option>
                           <option <?= $this->input->get('f') == 'OrderStatus' ? 'selected' :''; ?> value="OrderStatus">OrderStatus</option>
                           <option <?= $this->input->get('f') == 'OrderDiscountTotal' ? 'selected' :''; ?> value="OrderDiscountTotal">OrderDiscountTotal</option>
                           <option <?= $this->input->get('f') == 'OrderDiscountTax' ? 'selected' :''; ?> value="OrderDiscountTax">OrderDiscountTax</option>
                           <option <?= $this->input->get('f') == 'OrderShippingTotal' ? 'selected' :''; ?> value="OrderShippingTotal">OrderShippingTotal</option>
                           <option <?= $this->input->get('f') == 'OrderShippingTax' ? 'selected' :''; ?> value="OrderShippingTax">OrderShippingTax</option>
                           <option <?= $this->input->get('f') == 'OrderTotal' ? 'selected' :''; ?> value="OrderTotal">OrderTotal</option>
                          </select>
                     </div>
                     <div class="col-sm-1 padd-left-0 ">
                        <button type="submit" class="btn btn-flat" name="sbtn" id="sbtn" value="Apply" title="<?= cclang('filter_search'); ?>">
                        Filter
                        </button>
                     </div>
                     <div class="col-sm-1 padd-left-0 ">
                        <a class="btn btn-default btn-flat" name="reset" id="reset" value="Apply" href="<?= base_url('administrator/dawnwingapi');?>" title="<?= cclang('reset_filter'); ?>">
                        <i class="fa fa-undo"></i>
                        </a>
                     </div>
                  </div>
                  </form>                  <div class="col-md-4">
                     <div class="dataTables_paginate paging_simple_numbers pull-right" id="example2_paginate" >
                        <?= $pagination; ?>
                     </div>
                  </div>
               </div>
            </div>
            <!--/box body -->
         </div>
         <!--/box -->
      </div>
   </div>
</section>
<!-- /.content -->

<!-- Page script -->
<script>
  $(document).ready(function(){
   
    $('.remove-data').click(function(){

      var url = $(this).attr('data-href');

      swal({
          title: "<?= cclang('are_you_sure'); ?>",
          text: "<?= cclang('data_to_be_deleted_can_not_be_restored'); ?>",
          type: "warning",
          showCancelButton: true,
          confirmButtonColor: "#DD6B55",
          confirmButtonText: "<?= cclang('yes_delete_it'); ?>",
          cancelButtonText: "<?= cclang('no_cancel_plx'); ?>",
          closeOnConfirm: true,
          closeOnCancel: true
        },
        function(isConfirm){
          if (isConfirm) {
            document.location.href = url;            
          }
        });

      return false;
    });


    $('#apply').click(function(){

      var bulk = $('#bulk');
      var serialize_bulk = $('#form_dawnwingapi').serialize();

      if (bulk.val() == 'delete') {
         swal({
            title: "<?= cclang('are_you_sure'); ?>",
            text: "<?= cclang('data_to_be_deleted_can_not_be_restored'); ?>",
            type: "warning",
            showCancelButton: true,
            confirmButtonColor: "#DD6B55",
            confirmButtonText: "<?= cclang('yes_delete_it'); ?>",
            cancelButtonText: "<?= cclang('no_cancel_plx'); ?>",
            closeOnConfirm: true,
            closeOnCancel: true
          },
          function(isConfirm){
            if (isConfirm) {
               document.location.href = BASE_URL + '/administrator/dawnwingapi/delete?' + serialize_bulk;      
            }
          });

        return false;

      } else if(bulk.val() == '')  {
          swal({
            title: "Upss",
            text: "<?= cclang('please_choose_bulk_action_first'); ?>",
            type: "warning",
            showCancelButton: false,
            confirmButtonColor: "#DD6B55",
            confirmButtonText: "Okay!",
            closeOnConfirm: true,
            closeOnCancel: true
          });

        return false;
      }

      return false;

    });/*end appliy click*/


    //check all
    var checkAll = $('#check_all');
    var checkboxes = $('input.check');

    checkAll.on('ifChecked ifUnchecked', function(event) {   
        if (event.type == 'ifChecked') {
            checkboxes.iCheck('check');
        } else {
            checkboxes.iCheck('uncheck');
        }
    });

    checkboxes.on('ifChanged', function(event){
        if(checkboxes.filter(':checked').length == checkboxes.length) {
            checkAll.prop('checked', 'checked');
        } else {
            checkAll.removeProp('checked');
        }
        checkAll.iCheck('update');
    });

  }); /*end doc ready*/
</script>