
<script src="<?= BASE_ASSET; ?>/js/jquery.hotkeys.js"></script>

<script type="text/javascript">
//This page is a result of an autogenerated content made by running test.html with firefox.
function domo(){
 
   // Binding keys
   $('*').bind('keydown', 'Ctrl+a', function assets() {
       window.location.href = BASE_URL + '/administrator/Lbb_woocommerce_orders/add';
       return false;
   });

   $('*').bind('keydown', 'Ctrl+f', function assets() {
       $('#sbtn').trigger('click');
       return false;
   });

   $('*').bind('keydown', 'Ctrl+x', function assets() {
       $('#reset').trigger('click');
       return false;
   });

   $('*').bind('keydown', 'Ctrl+b', function assets() {

       $('#reset').trigger('click');
       return false;
   });
}

jQuery(document).ready(domo);
</script>
<!-- Content Header (Page header) -->
<section class="content-header">
   <h1>
      <?= cclang('lbb_woocommerce_orders') ?><small><?= cclang('list_all'); ?></small>
   </h1>
   <ol class="breadcrumb">
      <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
      <li class="active"><?= cclang('lbb_woocommerce_orders') ?></li>
   </ol>
</section>
<!-- Main content -->
<section class="content">
   <div class="row" >
      
      <div class="col-md-12">
         <div class="box box-warning">
            <div class="box-body ">
               <!-- Widget: user widget style 1 -->
               <div class="box box-widget widget-user-2">
                  <!-- Add the bg color to the header using any of the bg-* classes -->
                  <div class="widget-user-header ">
                     <div class="row pull-right">
                        <?php is_allowed('lbb_woocommerce_orders_add', function(){?>
                        <a class="btn btn-flat btn-success btn_add_new" id="btn_add_new" title="<?= cclang('add_new_button', [cclang('lbb_woocommerce_orders')]); ?>  (Ctrl+a)" href="<?=  site_url('administrator/lbb_woocommerce_orders/add'); ?>"><i class="fa fa-plus-square-o" ></i> <?= cclang('add_new_button', [cclang('lbb_woocommerce_orders')]); ?></a>
                        <?php }) ?>
                        <?php is_allowed('lbb_woocommerce_orders_export', function(){?>
                        <a class="btn btn-flat btn-success" title="<?= cclang('export'); ?> <?= cclang('lbb_woocommerce_orders') ?>']); ?>" href="<?= site_url('administrator/lbb_woocommerce_orders/export'); ?>"><i class="fa fa-file-excel-o" ></i> <?= cclang('export'); ?> XLS</a>
                        <?php }) ?>
                        <?php is_allowed('lbb_woocommerce_orders_export', function(){?>
                        <a class="btn btn-flat btn-success" title="<?= cclang('export'); ?> pdf <?= cclang('lbb_woocommerce_orders') ?>']); ?>" href="<?= site_url('administrator/lbb_woocommerce_orders/export_pdf'); ?>"><i class="fa fa-file-pdf-o" ></i> <?= cclang('export'); ?> PDF</a>
                        <?php }) ?>
                     </div>
                     <div class="widget-user-image">
                        <img class="img-circle" src="<?= BASE_ASSET; ?>/img/list.png" alt="User Avatar">
                     </div>
                     <!-- /.widget-user-image -->
                     <h3 class="widget-user-username"><?= cclang('lbb_woocommerce_orders') ?></h3>
                     <h5 class="widget-user-desc"><?= cclang('list_all', [cclang('lbb_woocommerce_orders')]); ?>  <i class="label bg-yellow"><?= $lbb_woocommerce_orders_counts; ?>  <?= cclang('items'); ?></i></h5>
                  </div>

                  <form name="form_lbb_woocommerce_orders" id="form_lbb_woocommerce_orders" action="<?= base_url('administrator/lbb_woocommerce_orders/index'); ?>">
                  

                  <div class="table-responsive"> 
                  <table class="table table-bordered table-striped dataTable">
                     <thead>
                        <tr class="">
                                                     <th>
                            <input type="checkbox" class="flat-red toltip" id="check_all" name="check_all" title="check all">
                           </th>
                                                    <th> <?= cclang('order_key') ?></th>
                           <th> <?= cclang('customer_id') ?></th>
                           <th> <?= cclang('billing_index') ?></th>
                           <th> <?= cclang('billing_first_name') ?></th>
                           <th> <?= cclang('billing_last_name') ?></th>
                           <th> <?= cclang('billing_company') ?></th>
                           <th> <?= cclang('billing_address_1') ?></th>
                           <th> <?= cclang('billing_address_2') ?></th>
                           <th> <?= cclang('billing_city') ?></th>
                           <th> <?= cclang('billing_state') ?></th>
                           <th> <?= cclang('billing_postcode') ?></th>
                           <th> <?= cclang('billing_country') ?></th>
                           <th> <?= cclang('billing_email') ?></th>
                           <th> <?= cclang('billing_phone') ?></th>
                           <th> <?= cclang('shipping_index') ?></th>
                           <th> <?= cclang('shipping_first_name') ?></th>
                           <th> <?= cclang('shipping_last_name') ?></th>
                           <th> <?= cclang('shipping_company') ?></th>
                           <th> <?= cclang('shipping_address_1') ?></th>
                           <th> <?= cclang('shipping_address_2') ?></th>
                           <th> <?= cclang('shipping_city') ?></th>
                           <th> <?= cclang('shipping_state') ?></th>
                           <th> <?= cclang('shipping_postcode') ?></th>
                           <th> <?= cclang('shipping_country') ?></th>
                           <th> <?= cclang('payment_method') ?></th>
                           <th> <?= cclang('payment_method_title') ?></th>
                           <th> <?= cclang('discount_total') ?></th>
                           <th> <?= cclang('discount_tax') ?></th>
                           <th> <?= cclang('shipping_total') ?></th>
                           <th> <?= cclang('shipping_tax') ?></th>
                           <th> <?= cclang('cart_tax') ?></th>
                           <th> <?= cclang('total') ?></th>
                           <th> <?= cclang('version') ?></th>
                           <th> <?= cclang('currency') ?></th>
                           <th> <?= cclang('prices_include_tax') ?></th>
                           <th> <?= cclang('transaction_id') ?></th>
                           <th> <?= cclang('customer_ip_address') ?></th>
                           <th> <?= cclang('customer_user_agent') ?></th>
                           <th> <?= cclang('created_via') ?></th>
                           <th> <?= cclang('date_completed') ?></th>
                           <th> <?= cclang('date_paid') ?></th>
                           <th> <?= cclang('cart_hash') ?></th>
                           <th> <?= cclang('amount') ?></th>
                           <th> <?= cclang('refunded_by') ?></th>
                           <th> <?= cclang('reason') ?></th>
                           <th>Action</th>                        </tr>
                     </thead>
                     <tbody id="tbody_lbb_woocommerce_orders">
                     <?php foreach($lbb_woocommerce_orderss as $lbb_woocommerce_orders): ?>
                        <tr>
                                                       <td width="5">
                              <input type="checkbox" class="flat-red check" name="id[]" value="<?= $lbb_woocommerce_orders->order_id; ?>">
                           </td>
                                                       
                           <td><?= _ent($lbb_woocommerce_orders->order_key); ?></td> 
                           <td><?= _ent($lbb_woocommerce_orders->customer_id); ?></td> 
                           <td><?= _ent($lbb_woocommerce_orders->billing_index); ?></td> 
                           <td><?= _ent($lbb_woocommerce_orders->billing_first_name); ?></td> 
                           <td><?= _ent($lbb_woocommerce_orders->billing_last_name); ?></td> 
                           <td><?= _ent($lbb_woocommerce_orders->billing_company); ?></td> 
                           <td><?= _ent($lbb_woocommerce_orders->billing_address_1); ?></td> 
                           <td><?= _ent($lbb_woocommerce_orders->billing_address_2); ?></td> 
                           <td><?= _ent($lbb_woocommerce_orders->billing_city); ?></td> 
                           <td><?= _ent($lbb_woocommerce_orders->billing_state); ?></td> 
                           <td><?= _ent($lbb_woocommerce_orders->billing_postcode); ?></td> 
                           <td><?= _ent($lbb_woocommerce_orders->billing_country); ?></td> 
                           <td><?= _ent($lbb_woocommerce_orders->billing_email); ?></td> 
                           <td><?= _ent($lbb_woocommerce_orders->billing_phone); ?></td> 
                           <td><?= _ent($lbb_woocommerce_orders->shipping_index); ?></td> 
                           <td><?= _ent($lbb_woocommerce_orders->shipping_first_name); ?></td> 
                           <td><?= _ent($lbb_woocommerce_orders->shipping_last_name); ?></td> 
                           <td><?= _ent($lbb_woocommerce_orders->shipping_company); ?></td> 
                           <td><?= _ent($lbb_woocommerce_orders->shipping_address_1); ?></td> 
                           <td><?= _ent($lbb_woocommerce_orders->shipping_address_2); ?></td> 
                           <td><?= _ent($lbb_woocommerce_orders->shipping_city); ?></td> 
                           <td><?= _ent($lbb_woocommerce_orders->shipping_state); ?></td> 
                           <td><?= _ent($lbb_woocommerce_orders->shipping_postcode); ?></td> 
                           <td><?= _ent($lbb_woocommerce_orders->shipping_country); ?></td> 
                           <td><?= _ent($lbb_woocommerce_orders->payment_method); ?></td> 
                           <td><?= _ent($lbb_woocommerce_orders->payment_method_title); ?></td> 
                           <td><?= _ent($lbb_woocommerce_orders->discount_total); ?></td> 
                           <td><?= _ent($lbb_woocommerce_orders->discount_tax); ?></td> 
                           <td><?= _ent($lbb_woocommerce_orders->shipping_total); ?></td> 
                           <td><?= _ent($lbb_woocommerce_orders->shipping_tax); ?></td> 
                           <td><?= _ent($lbb_woocommerce_orders->cart_tax); ?></td> 
                           <td><?= _ent($lbb_woocommerce_orders->total); ?></td> 
                           <td><?= _ent($lbb_woocommerce_orders->version); ?></td> 
                           <td><?= _ent($lbb_woocommerce_orders->currency); ?></td> 
                           <td><?= _ent($lbb_woocommerce_orders->prices_include_tax); ?></td> 
                           <td><?= _ent($lbb_woocommerce_orders->transaction_id); ?></td> 
                           <td><?= _ent($lbb_woocommerce_orders->customer_ip_address); ?></td> 
                           <td><?= _ent($lbb_woocommerce_orders->customer_user_agent); ?></td> 
                           <td><?= _ent($lbb_woocommerce_orders->created_via); ?></td> 
                           <td><?= _ent($lbb_woocommerce_orders->date_completed); ?></td> 
                           <td><?= _ent($lbb_woocommerce_orders->date_paid); ?></td> 
                           <td><?= _ent($lbb_woocommerce_orders->cart_hash); ?></td> 
                           <td><?= _ent($lbb_woocommerce_orders->amount); ?></td> 
                           <td><?= _ent($lbb_woocommerce_orders->refunded_by); ?></td> 
                           <td><?= _ent($lbb_woocommerce_orders->reason); ?></td> 
                           <td width="200">
                            
                                                              <?php is_allowed('lbb_woocommerce_orders_view', function() use ($lbb_woocommerce_orders){?>
                                 <a href="<?= site_url('administrator/lbb_woocommerce_orders/single_pdf/' .$lbb_woocommerce_orders->order_id); ?>" class="label-default"><i class="fa fa-file-pdf-o"></i> <?= cclang('PDF') ?>
                              <a href="<?= site_url('administrator/lbb_woocommerce_orders/view/' . $lbb_woocommerce_orders->order_id); ?>" class="label-default"><i class="fa fa-newspaper-o"></i> <?= cclang('view_button'); ?>
                              <?php }) ?>
                              <?php is_allowed('lbb_woocommerce_orders_update', function() use ($lbb_woocommerce_orders){?>
                              <a href="<?= site_url('administrator/lbb_woocommerce_orders/edit/' . $lbb_woocommerce_orders->order_id); ?>" class="label-default"><i class="fa fa-edit "></i> <?= cclang('update_button'); ?></a>
                              <?php }) ?>
                              <?php is_allowed('lbb_woocommerce_orders_delete', function() use ($lbb_woocommerce_orders){?>
                              <a href="javascript:void(0);" data-href="<?= site_url('administrator/lbb_woocommerce_orders/delete/' . $lbb_woocommerce_orders->order_id); ?>" class="label-default remove-data"><i class="fa fa-close"></i> <?= cclang('remove_button'); ?></a>
                               <?php }) ?>

                           </td>                        </tr>
                      <?php endforeach; ?>
                      <?php if ($lbb_woocommerce_orders_counts == 0) :?>
                         <tr>
                           <td colspan="100">
                           Lbb Woocommerce Orders data is not available
                           </td>
                         </tr>
                      <?php endif; ?>
                     </tbody>
                  </table>
                  </div>
               </div>
               <hr>
               <!-- /.widget-user -->
               <div class="row">
                  <div class="col-md-8">
                     <div class="col-sm-2 padd-left-0 " >
                        <select type="text" class="form-control chosen chosen-select" name="bulk" id="bulk" placeholder="Site Email" >
                           <option value="">Bulk</option>
                                                     <option value="delete">Delete</option>
                                                  </select>
                     </div>
                     <div class="col-sm-2 padd-left-0 ">
                        <button type="button" class="btn btn-flat" name="apply" id="apply" title="<?= cclang('apply_bulk_action'); ?>"><?= cclang('apply_button'); ?></button>
                     </div>
                     <div class="col-sm-3 padd-left-0  " >
                        <input type="text" class="form-control" name="q" id="filter" placeholder="<?= cclang('filter'); ?>" value="<?= $this->input->get('q'); ?>">
                     </div>
                     <div class="col-sm-3 padd-left-0 " >
                        <select type="text" class="form-control chosen chosen-select" name="f" id="field" >
                           <option value=""><?= cclang('all'); ?></option>
                            <option <?= $this->input->get('f') == 'order_key' ? 'selected' :''; ?> value="order_key">Order Key</option>
                           <option <?= $this->input->get('f') == 'customer_id' ? 'selected' :''; ?> value="customer_id">Customer Id</option>
                           <option <?= $this->input->get('f') == 'billing_index' ? 'selected' :''; ?> value="billing_index">Billing Index</option>
                           <option <?= $this->input->get('f') == 'billing_first_name' ? 'selected' :''; ?> value="billing_first_name">Billing First Name</option>
                           <option <?= $this->input->get('f') == 'billing_last_name' ? 'selected' :''; ?> value="billing_last_name">Billing Last Name</option>
                           <option <?= $this->input->get('f') == 'billing_company' ? 'selected' :''; ?> value="billing_company">Billing Company</option>
                           <option <?= $this->input->get('f') == 'billing_address_1' ? 'selected' :''; ?> value="billing_address_1">Billing Address 1</option>
                           <option <?= $this->input->get('f') == 'billing_address_2' ? 'selected' :''; ?> value="billing_address_2">Billing Address 2</option>
                           <option <?= $this->input->get('f') == 'billing_city' ? 'selected' :''; ?> value="billing_city">Billing City</option>
                           <option <?= $this->input->get('f') == 'billing_state' ? 'selected' :''; ?> value="billing_state">Billing State</option>
                           <option <?= $this->input->get('f') == 'billing_postcode' ? 'selected' :''; ?> value="billing_postcode">Billing Postcode</option>
                           <option <?= $this->input->get('f') == 'billing_country' ? 'selected' :''; ?> value="billing_country">Billing Country</option>
                           <option <?= $this->input->get('f') == 'billing_email' ? 'selected' :''; ?> value="billing_email">Billing Email</option>
                           <option <?= $this->input->get('f') == 'billing_phone' ? 'selected' :''; ?> value="billing_phone">Billing Phone</option>
                           <option <?= $this->input->get('f') == 'shipping_index' ? 'selected' :''; ?> value="shipping_index">Shipping Index</option>
                           <option <?= $this->input->get('f') == 'shipping_first_name' ? 'selected' :''; ?> value="shipping_first_name">Shipping First Name</option>
                           <option <?= $this->input->get('f') == 'shipping_last_name' ? 'selected' :''; ?> value="shipping_last_name">Shipping Last Name</option>
                           <option <?= $this->input->get('f') == 'shipping_company' ? 'selected' :''; ?> value="shipping_company">Shipping Company</option>
                           <option <?= $this->input->get('f') == 'shipping_address_1' ? 'selected' :''; ?> value="shipping_address_1">Shipping Address 1</option>
                           <option <?= $this->input->get('f') == 'shipping_address_2' ? 'selected' :''; ?> value="shipping_address_2">Shipping Address 2</option>
                           <option <?= $this->input->get('f') == 'shipping_city' ? 'selected' :''; ?> value="shipping_city">Shipping City</option>
                           <option <?= $this->input->get('f') == 'shipping_state' ? 'selected' :''; ?> value="shipping_state">Shipping State</option>
                           <option <?= $this->input->get('f') == 'shipping_postcode' ? 'selected' :''; ?> value="shipping_postcode">Shipping Postcode</option>
                           <option <?= $this->input->get('f') == 'shipping_country' ? 'selected' :''; ?> value="shipping_country">Shipping Country</option>
                           <option <?= $this->input->get('f') == 'payment_method' ? 'selected' :''; ?> value="payment_method">Payment Method</option>
                           <option <?= $this->input->get('f') == 'payment_method_title' ? 'selected' :''; ?> value="payment_method_title">Payment Method Title</option>
                           <option <?= $this->input->get('f') == 'discount_total' ? 'selected' :''; ?> value="discount_total">Discount Total</option>
                           <option <?= $this->input->get('f') == 'discount_tax' ? 'selected' :''; ?> value="discount_tax">Discount Tax</option>
                           <option <?= $this->input->get('f') == 'shipping_total' ? 'selected' :''; ?> value="shipping_total">Shipping Total</option>
                           <option <?= $this->input->get('f') == 'shipping_tax' ? 'selected' :''; ?> value="shipping_tax">Shipping Tax</option>
                           <option <?= $this->input->get('f') == 'cart_tax' ? 'selected' :''; ?> value="cart_tax">Cart Tax</option>
                           <option <?= $this->input->get('f') == 'total' ? 'selected' :''; ?> value="total">Total</option>
                           <option <?= $this->input->get('f') == 'version' ? 'selected' :''; ?> value="version">Version</option>
                           <option <?= $this->input->get('f') == 'currency' ? 'selected' :''; ?> value="currency">Currency</option>
                           <option <?= $this->input->get('f') == 'prices_include_tax' ? 'selected' :''; ?> value="prices_include_tax">Prices Include Tax</option>
                           <option <?= $this->input->get('f') == 'transaction_id' ? 'selected' :''; ?> value="transaction_id">Transaction Id</option>
                           <option <?= $this->input->get('f') == 'customer_ip_address' ? 'selected' :''; ?> value="customer_ip_address">Customer Ip Address</option>
                           <option <?= $this->input->get('f') == 'customer_user_agent' ? 'selected' :''; ?> value="customer_user_agent">Customer User Agent</option>
                           <option <?= $this->input->get('f') == 'created_via' ? 'selected' :''; ?> value="created_via">Created Via</option>
                           <option <?= $this->input->get('f') == 'date_completed' ? 'selected' :''; ?> value="date_completed">Date Completed</option>
                           <option <?= $this->input->get('f') == 'date_paid' ? 'selected' :''; ?> value="date_paid">Date Paid</option>
                           <option <?= $this->input->get('f') == 'cart_hash' ? 'selected' :''; ?> value="cart_hash">Cart Hash</option>
                           <option <?= $this->input->get('f') == 'amount' ? 'selected' :''; ?> value="amount">Amount</option>
                           <option <?= $this->input->get('f') == 'refunded_by' ? 'selected' :''; ?> value="refunded_by">Refunded By</option>
                           <option <?= $this->input->get('f') == 'reason' ? 'selected' :''; ?> value="reason">Reason</option>
                          </select>
                     </div>
                     <div class="col-sm-1 padd-left-0 ">
                        <button type="submit" class="btn btn-flat" name="sbtn" id="sbtn" value="Apply" title="<?= cclang('filter_search'); ?>">
                        Filter
                        </button>
                     </div>
                     <div class="col-sm-1 padd-left-0 ">
                        <a class="btn btn-default btn-flat" name="reset" id="reset" value="Apply" href="<?= base_url('administrator/lbb_woocommerce_orders');?>" title="<?= cclang('reset_filter'); ?>">
                        <i class="fa fa-undo"></i>
                        </a>
                     </div>
                  </div>
                  </form>                  <div class="col-md-4">
                     <div class="dataTables_paginate paging_simple_numbers pull-right" id="example2_paginate" >
                        <?= $pagination; ?>
                     </div>
                  </div>
               </div>
            </div>
            <!--/box body -->
         </div>
         <!--/box -->
      </div>
   </div>
</section>
<!-- /.content -->

<!-- Page script -->
<script>
  $(document).ready(function(){
   
    $('.remove-data').click(function(){

      var url = $(this).attr('data-href');

      swal({
          title: "<?= cclang('are_you_sure'); ?>",
          text: "<?= cclang('data_to_be_deleted_can_not_be_restored'); ?>",
          type: "warning",
          showCancelButton: true,
          confirmButtonColor: "#DD6B55",
          confirmButtonText: "<?= cclang('yes_delete_it'); ?>",
          cancelButtonText: "<?= cclang('no_cancel_plx'); ?>",
          closeOnConfirm: true,
          closeOnCancel: true
        },
        function(isConfirm){
          if (isConfirm) {
            document.location.href = url;            
          }
        });

      return false;
    });


    $('#apply').click(function(){

      var bulk = $('#bulk');
      var serialize_bulk = $('#form_lbb_woocommerce_orders').serialize();

      if (bulk.val() == 'delete') {
         swal({
            title: "<?= cclang('are_you_sure'); ?>",
            text: "<?= cclang('data_to_be_deleted_can_not_be_restored'); ?>",
            type: "warning",
            showCancelButton: true,
            confirmButtonColor: "#DD6B55",
            confirmButtonText: "<?= cclang('yes_delete_it'); ?>",
            cancelButtonText: "<?= cclang('no_cancel_plx'); ?>",
            closeOnConfirm: true,
            closeOnCancel: true
          },
          function(isConfirm){
            if (isConfirm) {
               document.location.href = BASE_URL + '/administrator/lbb_woocommerce_orders/delete?' + serialize_bulk;      
            }
          });

        return false;

      } else if(bulk.val() == '')  {
          swal({
            title: "Upss",
            text: "<?= cclang('please_choose_bulk_action_first'); ?>",
            type: "warning",
            showCancelButton: false,
            confirmButtonColor: "#DD6B55",
            confirmButtonText: "Okay!",
            closeOnConfirm: true,
            closeOnCancel: true
          });

        return false;
      }

      return false;

    });/*end appliy click*/


    //check all
    var checkAll = $('#check_all');
    var checkboxes = $('input.check');

    checkAll.on('ifChecked ifUnchecked', function(event) {   
        if (event.type == 'ifChecked') {
            checkboxes.iCheck('check');
        } else {
            checkboxes.iCheck('uncheck');
        }
    });

    checkboxes.on('ifChanged', function(event){
        if(checkboxes.filter(':checked').length == checkboxes.length) {
            checkAll.prop('checked', 'checked');
        } else {
            checkAll.removeProp('checked');
        }
        checkAll.iCheck('update');
    });

  }); /*end doc ready*/
</script>