
<script src="<?= BASE_ASSET; ?>/js/jquery.hotkeys.js"></script>
<script type="text/javascript">
//This page is a result of an autogenerated content made by running test.html with firefox.
function domo(){
 
   // Binding keys
   $('*').bind('keydown', 'Ctrl+e', function assets() {
      $('#btn_edit').trigger('click');
       return false;
   });

   $('*').bind('keydown', 'Ctrl+x', function assets() {
      $('#btn_back').trigger('click');
       return false;
   });
    
}


jQuery(document).ready(domo);
</script>
<!-- Content Header (Page header) -->
<section class="content-header">
   <h1>
      Wp Woocommerce Orders      <small><?= cclang('detail', ['Wp Woocommerce Orders']); ?> </small>
   </h1>
   <ol class="breadcrumb">
      <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
      <li class=""><a  href="<?= site_url('administrator/wp_woocommerce_orders'); ?>">Wp Woocommerce Orders</a></li>
      <li class="active"><?= cclang('detail'); ?></li>
   </ol>
</section>
<!-- Main content -->
<section class="content">
   <div class="row" >
     
      <div class="col-md-12">
         <div class="box box-warning">
            <div class="box-body ">

               <!-- Widget: user widget style 1 -->
               <div class="box box-widget widget-user-2">
                  <!-- Add the bg color to the header using any of the bg-* classes -->
                  <div class="widget-user-header ">
                    
                     <div class="widget-user-image">
                        <img class="img-circle" src="<?= BASE_ASSET; ?>/img/view.png" alt="User Avatar">
                     </div>
                     <!-- /.widget-user-image -->
                     <h3 class="widget-user-username">Wp Woocommerce Orders</h3>
                     <h5 class="widget-user-desc">Detail Wp Woocommerce Orders</h5>
                     <hr>
                  </div>

                 
                  <div class="form-horizontal" name="form_wp_woocommerce_orders" id="form_wp_woocommerce_orders" >
                   
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Order Id </label>

                        <div class="col-sm-8">
                           <?= _ent($wp_woocommerce_orders->order_id); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Order Key </label>

                        <div class="col-sm-8">
                           <?= _ent($wp_woocommerce_orders->order_key); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Customer Id </label>

                        <div class="col-sm-8">
                           <?= _ent($wp_woocommerce_orders->customer_id); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Billing Index </label>

                        <div class="col-sm-8">
                           <?= _ent($wp_woocommerce_orders->billing_index); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Billing First Name </label>

                        <div class="col-sm-8">
                           <?= _ent($wp_woocommerce_orders->billing_first_name); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Billing Last Name </label>

                        <div class="col-sm-8">
                           <?= _ent($wp_woocommerce_orders->billing_last_name); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Billing Company </label>

                        <div class="col-sm-8">
                           <?= _ent($wp_woocommerce_orders->billing_company); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Billing Address 1 </label>

                        <div class="col-sm-8">
                           <?= _ent($wp_woocommerce_orders->billing_address_1); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Billing Address 2 </label>

                        <div class="col-sm-8">
                           <?= _ent($wp_woocommerce_orders->billing_address_2); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Billing City </label>

                        <div class="col-sm-8">
                           <?= _ent($wp_woocommerce_orders->billing_city); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Billing State </label>

                        <div class="col-sm-8">
                           <?= _ent($wp_woocommerce_orders->billing_state); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Billing Postcode </label>

                        <div class="col-sm-8">
                           <?= _ent($wp_woocommerce_orders->billing_postcode); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Billing Country </label>

                        <div class="col-sm-8">
                           <?= _ent($wp_woocommerce_orders->billing_country); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Billing Email </label>

                        <div class="col-sm-8">
                           <?= _ent($wp_woocommerce_orders->billing_email); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Billing Phone </label>

                        <div class="col-sm-8">
                           <?= _ent($wp_woocommerce_orders->billing_phone); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Shipping Index </label>

                        <div class="col-sm-8">
                           <?= _ent($wp_woocommerce_orders->shipping_index); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Shipping First Name </label>

                        <div class="col-sm-8">
                           <?= _ent($wp_woocommerce_orders->shipping_first_name); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Shipping Last Name </label>

                        <div class="col-sm-8">
                           <?= _ent($wp_woocommerce_orders->shipping_last_name); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Shipping Company </label>

                        <div class="col-sm-8">
                           <?= _ent($wp_woocommerce_orders->shipping_company); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Shipping Address 1 </label>

                        <div class="col-sm-8">
                           <?= _ent($wp_woocommerce_orders->shipping_address_1); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Shipping Address 2 </label>

                        <div class="col-sm-8">
                           <?= _ent($wp_woocommerce_orders->shipping_address_2); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Shipping City </label>

                        <div class="col-sm-8">
                           <?= _ent($wp_woocommerce_orders->shipping_city); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Shipping State </label>

                        <div class="col-sm-8">
                           <?= _ent($wp_woocommerce_orders->shipping_state); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Shipping Postcode </label>

                        <div class="col-sm-8">
                           <?= _ent($wp_woocommerce_orders->shipping_postcode); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Shipping Country </label>

                        <div class="col-sm-8">
                           <?= _ent($wp_woocommerce_orders->shipping_country); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Payment Method </label>

                        <div class="col-sm-8">
                           <?= _ent($wp_woocommerce_orders->payment_method); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Payment Method Title </label>

                        <div class="col-sm-8">
                           <?= _ent($wp_woocommerce_orders->payment_method_title); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Discount Total </label>

                        <div class="col-sm-8">
                           <?= _ent($wp_woocommerce_orders->discount_total); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Discount Tax </label>

                        <div class="col-sm-8">
                           <?= _ent($wp_woocommerce_orders->discount_tax); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Shipping Total </label>

                        <div class="col-sm-8">
                           <?= _ent($wp_woocommerce_orders->shipping_total); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Shipping Tax </label>

                        <div class="col-sm-8">
                           <?= _ent($wp_woocommerce_orders->shipping_tax); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Cart Tax </label>

                        <div class="col-sm-8">
                           <?= _ent($wp_woocommerce_orders->cart_tax); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Total </label>

                        <div class="col-sm-8">
                           <?= _ent($wp_woocommerce_orders->total); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Version </label>

                        <div class="col-sm-8">
                           <?= _ent($wp_woocommerce_orders->version); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Currency </label>

                        <div class="col-sm-8">
                           <?= _ent($wp_woocommerce_orders->currency); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Prices Include Tax </label>

                        <div class="col-sm-8">
                           <?= _ent($wp_woocommerce_orders->prices_include_tax); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Transaction Id </label>

                        <div class="col-sm-8">
                           <?= _ent($wp_woocommerce_orders->transaction_id); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Customer Ip Address </label>

                        <div class="col-sm-8">
                           <?= _ent($wp_woocommerce_orders->customer_ip_address); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Customer User Agent </label>

                        <div class="col-sm-8">
                           <?= _ent($wp_woocommerce_orders->customer_user_agent); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Created Via </label>

                        <div class="col-sm-8">
                           <?= _ent($wp_woocommerce_orders->created_via); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Date Completed </label>

                        <div class="col-sm-8">
                           <?= _ent($wp_woocommerce_orders->date_completed); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Date Paid </label>

                        <div class="col-sm-8">
                           <?= _ent($wp_woocommerce_orders->date_paid); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Cart Hash </label>

                        <div class="col-sm-8">
                           <?= _ent($wp_woocommerce_orders->cart_hash); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Amount </label>

                        <div class="col-sm-8">
                           <?= _ent($wp_woocommerce_orders->amount); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Refunded By </label>

                        <div class="col-sm-8">
                           <?= _ent($wp_woocommerce_orders->refunded_by); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Reason </label>

                        <div class="col-sm-8">
                           <?= _ent($wp_woocommerce_orders->reason); ?>
                        </div>
                    </div>
                                        
                    <br>
                    <br>

                    <div class="view-nav">
                        <?php is_allowed('wp_woocommerce_orders_update', function() use ($wp_woocommerce_orders){?>
                        <a class="btn btn-flat btn-info btn_edit btn_action" id="btn_edit" data-stype='back' title="edit wp_woocommerce_orders (Ctrl+e)" href="<?= site_url('administrator/wp_woocommerce_orders/edit/'.$wp_woocommerce_orders->order_id); ?>"><i class="fa fa-edit" ></i> <?= cclang('update', ['Wp Woocommerce Orders']); ?> </a>
                        <?php }) ?>
                        <a class="btn btn-flat btn-default btn_action" id="btn_back" title="back (Ctrl+x)" href="<?= site_url('administrator/wp_woocommerce_orders/'); ?>"><i class="fa fa-undo" ></i> <?= cclang('go_list_button', ['Wp Woocommerce Orders']); ?></a>
                     </div>
                    
                  </div>
               </div>
            </div>
            <!--/box body -->
         </div>
         <!--/box -->

      </div>
   </div>
</section>
<!-- /.content -->
