
<script src="<?= BASE_ASSET; ?>/js/jquery.hotkeys.js"></script>

<script type="text/javascript">
//This page is a result of an autogenerated content made by running test.html with firefox.
function domo(){
 
   // Binding keys
   $('*').bind('keydown', 'Ctrl+a', function assets() {
       window.location.href = BASE_URL + '/administrator/Siteproduct/add';
       return false;
   });

   $('*').bind('keydown', 'Ctrl+f', function assets() {
       $('#sbtn').trigger('click');
       return false;
   });

   $('*').bind('keydown', 'Ctrl+x', function assets() {
       $('#reset').trigger('click');
       return false;
   });

   $('*').bind('keydown', 'Ctrl+b', function assets() {

       $('#reset').trigger('click');
       return false;
   });
}

jQuery(document).ready(domo);
</script>
<!-- Content Header (Page header) -->
<section class="content-header">
   <h1>
      <?= cclang('siteproduct') ?><small><?= cclang('list_all'); ?></small>
   </h1>
   <ol class="breadcrumb">
      <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
      <li class="active"><?= cclang('siteproduct') ?></li>
   </ol>
</section>
<!-- Main content -->
<section class="content">
   <div class="row" >
      
      <div class="col-md-12">
         <div class="box box-warning">
            <div class="box-body ">
               <!-- Widget: user widget style 1 -->
               <div class="box box-widget widget-user-2">
                  <!-- Add the bg color to the header using any of the bg-* classes -->
                  <div class="widget-user-header ">
                     <div class="row pull-right">
                        <?php is_allowed('siteproduct_add', function(){?>
                        <a class="btn btn-flat btn-success btn_add_new" id="btn_add_new" title="<?= cclang('add_new_button', [cclang('siteproduct')]); ?>  (Ctrl+a)" href="<?=  site_url('administrator/siteproduct/add'); ?>"><i class="fa fa-plus-square-o" ></i> <?= cclang('add_new_button', [cclang('siteproduct')]); ?></a>
                        <?php }) ?>
                        <?php is_allowed('siteproduct_export', function(){?>
                        <a class="btn btn-flat btn-success" title="<?= cclang('export'); ?> <?= cclang('siteproduct') ?>']); ?>" href="<?= site_url('administrator/siteproduct/export'); ?>"><i class="fa fa-file-excel-o" ></i> <?= cclang('export'); ?> XLS</a>
                        <?php }) ?>
                        <?php is_allowed('siteproduct_export', function(){?>
                        <a class="btn btn-flat btn-success" title="<?= cclang('export'); ?> pdf <?= cclang('siteproduct') ?>']); ?>" href="<?= site_url('administrator/siteproduct/export_pdf'); ?>"><i class="fa fa-file-pdf-o" ></i> <?= cclang('export'); ?> PDF</a>
                        <?php }) ?>
                     </div>
                     <div class="widget-user-image">
                        <img class="img-circle" src="<?= BASE_ASSET; ?>/img/list.png" alt="User Avatar">
                     </div>
                     <!-- /.widget-user-image -->
                     <h3 class="widget-user-username"><?= cclang('siteproduct') ?></h3>
                     <h5 class="widget-user-desc"><?= cclang('list_all', [cclang('siteproduct')]); ?>  <i class="label bg-yellow"><?= $siteproduct_counts; ?>  <?= cclang('items'); ?></i></h5>
                  </div>

                  <form name="form_siteproduct" id="form_siteproduct" action="<?= base_url('administrator/siteproduct/index'); ?>">
                  

                  <div class="table-responsive"> 
                  <table class="table table-bordered table-striped dataTable">
                     <thead>
                        <tr class="">
                                                     <th>
                            <input type="checkbox" class="flat-red toltip" id="check_all" name="check_all" title="check all">
                           </th>
                                                    <th> <?= cclang('id') ?></th>
                           <th> <?= cclang('product_name') ?></th>
                           <th> <?= cclang('sku') ?></th>
                           <th> <?= cclang('category_main') ?></th>
                           <th> <?= cclang('category_sub') ?></th>
                           <th> <?= cclang('brand') ?></th>
                           <th> <?= cclang('simpleorvariant') ?></th>
                           <th> <?= cclang('price') ?></th>
                           <th> <?= cclang('description') ?></th>
                           <th> <?= cclang('whatsinthebox') ?></th>
                           <th> <?= cclang('first_image') ?></th>
                           <th> <?= cclang('second_image') ?></th>
                           <th> <?= cclang('gallery') ?></th>
                           <th> <?= cclang('website') ?></th>
                           <th> <?= cclang('status') ?></th>
                           <th> <?= cclang('created_at') ?></th>
                           <th>Action</th>                        </tr>
                     </thead>
                     <tbody id="tbody_siteproduct">
                     <?php foreach($siteproducts as $siteproduct): ?>
                        <tr>
                                                       <td width="5">
                              <input type="checkbox" class="flat-red check" name="id[]" value="<?= $siteproduct->id; ?>">
                           </td>
                                                       
                           <td><?= _ent($siteproduct->id); ?></td> 
                           <td><?= _ent($siteproduct->product_name); ?></td> 
                           <td><?= _ent($siteproduct->sku); ?></td> 
                           <td><?= join_multi_select($siteproduct->category_main, 'category_main', 'category_name', 'category_name'); ?></td> 
                           <td><?= join_multi_select($siteproduct->category_sub, 'category_sub', 'category_sub_name', 'category_sub_name'); ?></td> 
                           <td><?= join_multi_select($siteproduct->brand, 'brand', 'brand_name', 'brand_name'); ?></td> 
                           <td><?= join_multi_select($siteproduct->simpleorvariant, 'form_single_or_variant', 'id', 'id'); ?></td> 
                           <td><?= _ent($siteproduct->price); ?></td> 
                           <td><?= _ent($siteproduct->description); ?></td> 
                           <td><?= _ent($siteproduct->whatsinthebox); ?></td> 
                           <td>
                              <?php if (!empty($siteproduct->first_image)): ?>
                                <?php if (is_image($siteproduct->first_image)): ?>
                                <a class="fancybox" rel="group" href="<?= BASE_URL . 'uploads/siteproduct/' . $siteproduct->first_image; ?>">
                                  <img src="<?= BASE_URL . 'uploads/siteproduct/' . $siteproduct->first_image; ?>" class="image-responsive" alt="image siteproduct" title="first_image siteproduct" width="40px">
                                </a>
                                <?php else: ?>
                                  <a href="<?= BASE_URL . 'uploads/siteproduct/' . $siteproduct->first_image; ?>">
                                   <img src="<?= get_icon_file($siteproduct->first_image); ?>" class="image-responsive image-icon" alt="image siteproduct" title="first_image <?= $siteproduct->first_image; ?>" width="40px"> 
                                 </a>
                                <?php endif; ?>
                              <?php endif; ?>
                           </td>
                            
                           <td>
                              <?php if (!empty($siteproduct->second_image)): ?>
                                <?php if (is_image($siteproduct->second_image)): ?>
                                <a class="fancybox" rel="group" href="<?= BASE_URL . 'uploads/siteproduct/' . $siteproduct->second_image; ?>">
                                  <img src="<?= BASE_URL . 'uploads/siteproduct/' . $siteproduct->second_image; ?>" class="image-responsive" alt="image siteproduct" title="second_image siteproduct" width="40px">
                                </a>
                                <?php else: ?>
                                  <a href="<?= BASE_URL . 'uploads/siteproduct/' . $siteproduct->second_image; ?>">
                                   <img src="<?= get_icon_file($siteproduct->second_image); ?>" class="image-responsive image-icon" alt="image siteproduct" title="second_image <?= $siteproduct->second_image; ?>" width="40px"> 
                                 </a>
                                <?php endif; ?>
                              <?php endif; ?>
                           </td>
                            
                           <td>
                              <?php foreach (explode(',', $siteproduct->gallery) as $file): ?>
                              <?php if (!empty($file)): ?>
                                <?php if (is_image($file)): ?>
                                <a class="fancybox" rel="group" href="<?= BASE_URL . 'uploads/siteproduct/' . $file; ?>">
                                  <img src="<?= BASE_URL . 'uploads/siteproduct/' . $file; ?>" class="image-responsive" alt="image siteproduct" title="gallery siteproduct" width="40px">
                                </a>
                                <?php else: ?>
                                  <a href="<?= BASE_URL . 'uploads/siteproduct/' . $file; ?>">
                                   <img src="<?= get_icon_file($file); ?>" class="image-responsive image-icon" alt="image siteproduct" title="gallery <?= $file; ?>" width="40px"> 
                                 </a>
                                <?php endif; ?>
                              <?php endif; ?>
                              <?php endforeach; ?>
                           </td>
                            
                           <td><?= join_multi_select($siteproduct->website, 'website', 'website_name', 'website_name'); ?></td> 
                           <td><?= join_multi_select($siteproduct->status, 'status', 'status_name', 'status_name'); ?></td> 
                           <td><?= _ent($siteproduct->created_at); ?></td> 
                           <td width="200">
                            
                                                              <?php is_allowed('siteproduct_view', function() use ($siteproduct){?>
                                 <a href="<?= site_url('administrator/siteproduct/single_pdf/' .$siteproduct->id); ?>" class="label-default"><i class="fa fa-file-pdf-o"></i> <?= cclang('PDF') ?>
                              <a href="<?= site_url('administrator/siteproduct/view/' . $siteproduct->id); ?>" class="label-default"><i class="fa fa-newspaper-o"></i> <?= cclang('view_button'); ?>
                              <?php }) ?>
                              <?php is_allowed('siteproduct_update', function() use ($siteproduct){?>
                              <a href="<?= site_url('administrator/siteproduct/edit/' . $siteproduct->id); ?>" class="label-default"><i class="fa fa-edit "></i> <?= cclang('update_button'); ?></a>
                              <?php }) ?>
                              <?php is_allowed('siteproduct_delete', function() use ($siteproduct){?>
                              <a href="javascript:void(0);" data-href="<?= site_url('administrator/siteproduct/delete/' . $siteproduct->id); ?>" class="label-default remove-data"><i class="fa fa-close"></i> <?= cclang('remove_button'); ?></a>
                               <?php }) ?>

                           </td>                        </tr>
                      <?php endforeach; ?>
                      <?php if ($siteproduct_counts == 0) :?>
                         <tr>
                           <td colspan="100">
                           Products data is not available
                           </td>
                         </tr>
                      <?php endif; ?>
                     </tbody>
                  </table>
                  </div>
               </div>
               <hr>
               <!-- /.widget-user -->
               <div class="row">
                  <div class="col-md-8">
                     <div class="col-sm-2 padd-left-0 " >
                        <select type="text" class="form-control chosen chosen-select" name="bulk" id="bulk" placeholder="Site Email" >
                           <option value="">Bulk</option>
                                                     <option value="delete">Delete</option>
                                                  </select>
                     </div>
                     <div class="col-sm-2 padd-left-0 ">
                        <button type="button" class="btn btn-flat" name="apply" id="apply" title="<?= cclang('apply_bulk_action'); ?>"><?= cclang('apply_button'); ?></button>
                     </div>
                     <div class="col-sm-3 padd-left-0  " >
                        <input type="text" class="form-control" name="q" id="filter" placeholder="<?= cclang('filter'); ?>" value="<?= $this->input->get('q'); ?>">
                     </div>
                     <div class="col-sm-3 padd-left-0 " >
                        <select type="text" class="form-control chosen chosen-select" name="f" id="field" >
                           <option value=""><?= cclang('all'); ?></option>
                            <option <?= $this->input->get('f') == 'id' ? 'selected' :''; ?> value="id">Id</option>
                           <option <?= $this->input->get('f') == 'product_name' ? 'selected' :''; ?> value="product_name">Name</option>
                           <option <?= $this->input->get('f') == 'sku' ? 'selected' :''; ?> value="sku">SKU</option>
                           <option <?= $this->input->get('f') == 'category_main' ? 'selected' :''; ?> value="category_main">Parent</option>
                           <option <?= $this->input->get('f') == 'category_sub' ? 'selected' :''; ?> value="category_sub">Child</option>
                           <option <?= $this->input->get('f') == 'brand' ? 'selected' :''; ?> value="brand">Brands</option>
                           <option <?= $this->input->get('f') == 'simpleorvariant' ? 'selected' :''; ?> value="simpleorvariant">Type</option>
                           <option <?= $this->input->get('f') == 'price' ? 'selected' :''; ?> value="price">Price</option>
                           <option <?= $this->input->get('f') == 'description' ? 'selected' :''; ?> value="description">Desc</option>
                           <option <?= $this->input->get('f') == 'whatsinthebox' ? 'selected' :''; ?> value="whatsinthebox">WITB</option>
                           <option <?= $this->input->get('f') == 'first_image' ? 'selected' :''; ?> value="first_image">First</option>
                           <option <?= $this->input->get('f') == 'second_image' ? 'selected' :''; ?> value="second_image">Second</option>
                           <option <?= $this->input->get('f') == 'gallery' ? 'selected' :''; ?> value="gallery">Gallery</option>
                           <option <?= $this->input->get('f') == 'website' ? 'selected' :''; ?> value="website">Websites</option>
                           <option <?= $this->input->get('f') == 'status' ? 'selected' :''; ?> value="status">Status</option>
                           <option <?= $this->input->get('f') == 'created_at' ? 'selected' :''; ?> value="created_at">Updated</option>
                          </select>
                     </div>
                     <div class="col-sm-1 padd-left-0 ">
                        <button type="submit" class="btn btn-flat" name="sbtn" id="sbtn" value="Apply" title="<?= cclang('filter_search'); ?>">
                        Filter
                        </button>
                     </div>
                     <div class="col-sm-1 padd-left-0 ">
                        <a class="btn btn-default btn-flat" name="reset" id="reset" value="Apply" href="<?= base_url('administrator/siteproduct');?>" title="<?= cclang('reset_filter'); ?>">
                        <i class="fa fa-undo"></i>
                        </a>
                     </div>
                  </div>
                  </form>                  <div class="col-md-4">
                     <div class="dataTables_paginate paging_simple_numbers pull-right" id="example2_paginate" >
                        <?= $pagination; ?>
                     </div>
                  </div>
               </div>
            </div>
            <!--/box body -->
         </div>
         <!--/box -->
      </div>
   </div>
</section>
<!-- /.content -->

<!-- Page script -->
<script>
  $(document).ready(function(){
   
    $('.remove-data').click(function(){

      var url = $(this).attr('data-href');

      swal({
          title: "<?= cclang('are_you_sure'); ?>",
          text: "<?= cclang('data_to_be_deleted_can_not_be_restored'); ?>",
          type: "warning",
          showCancelButton: true,
          confirmButtonColor: "#DD6B55",
          confirmButtonText: "<?= cclang('yes_delete_it'); ?>",
          cancelButtonText: "<?= cclang('no_cancel_plx'); ?>",
          closeOnConfirm: true,
          closeOnCancel: true
        },
        function(isConfirm){
          if (isConfirm) {
            document.location.href = url;            
          }
        });

      return false;
    });


    $('#apply').click(function(){

      var bulk = $('#bulk');
      var serialize_bulk = $('#form_siteproduct').serialize();

      if (bulk.val() == 'delete') {
         swal({
            title: "<?= cclang('are_you_sure'); ?>",
            text: "<?= cclang('data_to_be_deleted_can_not_be_restored'); ?>",
            type: "warning",
            showCancelButton: true,
            confirmButtonColor: "#DD6B55",
            confirmButtonText: "<?= cclang('yes_delete_it'); ?>",
            cancelButtonText: "<?= cclang('no_cancel_plx'); ?>",
            closeOnConfirm: true,
            closeOnCancel: true
          },
          function(isConfirm){
            if (isConfirm) {
               document.location.href = BASE_URL + '/administrator/siteproduct/delete?' + serialize_bulk;      
            }
          });

        return false;

      } else if(bulk.val() == '')  {
          swal({
            title: "Upss",
            text: "<?= cclang('please_choose_bulk_action_first'); ?>",
            type: "warning",
            showCancelButton: false,
            confirmButtonColor: "#DD6B55",
            confirmButtonText: "Okay!",
            closeOnConfirm: true,
            closeOnCancel: true
          });

        return false;
      }

      return false;

    });/*end appliy click*/


    //check all
    var checkAll = $('#check_all');
    var checkboxes = $('input.check');

    checkAll.on('ifChecked ifUnchecked', function(event) {   
        if (event.type == 'ifChecked') {
            checkboxes.iCheck('check');
        } else {
            checkboxes.iCheck('uncheck');
        }
    });

    checkboxes.on('ifChanged', function(event){
        if(checkboxes.filter(':checked').length == checkboxes.length) {
            checkAll.prop('checked', 'checked');
        } else {
            checkAll.removeProp('checked');
        }
        checkAll.iCheck('update');
    });

  }); /*end doc ready*/
</script>