
<script src="<?= BASE_ASSET; ?>/js/jquery.hotkeys.js"></script>

<script type="text/javascript">
//This page is a result of an autogenerated content made by running test.html with firefox.
function domo(){
 
   // Binding keys
   $('*').bind('keydown', 'Ctrl+a', function assets() {
       window.location.href = BASE_URL + '/administrator/Api_orders/add';
       return false;
   });

   $('*').bind('keydown', 'Ctrl+f', function assets() {
       $('#sbtn').trigger('click');
       return false;
   });

   $('*').bind('keydown', 'Ctrl+x', function assets() {
       $('#reset').trigger('click');
       return false;
   });

   $('*').bind('keydown', 'Ctrl+b', function assets() {

       $('#reset').trigger('click');
       return false;
   });
}

jQuery(document).ready(domo);
</script>
<!-- Content Header (Page header) -->
<section class="content-header">
   <h1>
      <?= cclang('api_orders') ?><small><?= cclang('list_all'); ?></small>
   </h1>
   <ol class="breadcrumb">
      <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
      <li class="active"><?= cclang('api_orders') ?></li>
   </ol>
</section>
<!-- Main content -->
<section class="content">
   <div class="row" >
      
      <div class="col-md-12">
         <div class="box box-warning">
            <div class="box-body ">
               <!-- Widget: user widget style 1 -->
               <div class="box box-widget widget-user-2">
                  <!-- Add the bg color to the header using any of the bg-* classes -->
                  <div class="widget-user-header ">
                     <div class="row pull-right">
                        <?php is_allowed('api_orders_add', function(){?>
                        <a class="btn btn-flat btn-success btn_add_new" id="btn_add_new" title="<?= cclang('add_new_button', [cclang('api_orders')]); ?>  (Ctrl+a)" href="<?=  site_url('administrator/api_orders/add'); ?>"><i class="fa fa-plus-square-o" ></i> <?= cclang('add_new_button', [cclang('api_orders')]); ?></a>
                        <?php }) ?>
                        <?php is_allowed('api_orders_export', function(){?>
                        <a class="btn btn-flat btn-success" title="<?= cclang('export'); ?> <?= cclang('api_orders') ?>']); ?>" href="<?= site_url('administrator/api_orders/export'); ?>"><i class="fa fa-file-excel-o" ></i> <?= cclang('export'); ?> XLS</a>
                        <?php }) ?>
                        <?php is_allowed('api_orders_export', function(){?>
                        <a class="btn btn-flat btn-success" title="<?= cclang('export'); ?> pdf <?= cclang('api_orders') ?>']); ?>" href="<?= site_url('administrator/api_orders/export_pdf'); ?>"><i class="fa fa-file-pdf-o" ></i> <?= cclang('export'); ?> PDF</a>
                        <?php }) ?>
                     </div>
                     <div class="widget-user-image">
                        <img class="img-circle" src="<?= BASE_ASSET; ?>/img/list.png" alt="User Avatar">
                     </div>
                     <!-- /.widget-user-image -->
                     <h3 class="widget-user-username"><?= cclang('api_orders') ?></h3>
                     <h5 class="widget-user-desc"><?= cclang('list_all', [cclang('api_orders')]); ?>  <i class="label bg-yellow"><?= $api_orders_counts; ?>  <?= cclang('items'); ?></i></h5>
                  </div>

                  <form name="form_api_orders" id="form_api_orders" action="<?= base_url('administrator/api_orders/index'); ?>">
                  

                  <div class="table-responsive"> 
                  <table class="table table-bordered table-striped dataTable">
                     <thead>
                        <tr class="">
                                                     <th>
                            <input type="checkbox" class="flat-red toltip" id="check_all" name="check_all" title="check all">
                           </th>
                                                    <th> <?= cclang('id') ?></th>
                           <th> <?= cclang('user_id') ?></th>
                           <th> <?= cclang('order_number') ?></th>
                           <th> <?= cclang('order_parent_id') ?></th>
                           <th> <?= cclang('order_status') ?></th>
                           <th> <?= cclang('order_currency') ?></th>
                           <th> <?= cclang('order_version') ?></th>
                           <th> <?= cclang('order_payment_method') ?></th>
                           <th> <?= cclang('order_payment_method_title') ?></th>
                           <th> <?= cclang('order_date_created') ?></th>
                           <th> <?= cclang('order_date_modified') ?></th>
                           <th> <?= cclang('order_timestamp_created') ?></th>
                           <th> <?= cclang('order_timestamp_modified') ?></th>
                           <th> <?= cclang('order_discount_total') ?></th>
                           <th> <?= cclang('order_discount_tax') ?></th>
                           <th> <?= cclang('order_shipping_total') ?></th>
                           <th> <?= cclang('order_shipping_tax') ?></th>
                           <th> <?= cclang('order_total_tax') ?></th>
                           <th> <?= cclang('order_customer_id') ?></th>
                           <th> <?= cclang('order_billing_first_name') ?></th>
                           <th> <?= cclang('order_billing_last_name') ?></th>
                           <th> <?= cclang('order_billing_company') ?></th>
                           <th> <?= cclang('order_billing_address_1') ?></th>
                           <th> <?= cclang('order_billing_city') ?></th>
                           <th> <?= cclang('order_billing_state') ?></th>
                           <th> <?= cclang('order_billing_postcode') ?></th>
                           <th> <?= cclang('order_billing_country') ?></th>
                           <th> <?= cclang('order_billing_email') ?></th>
                           <th> <?= cclang('order_billing_phone') ?></th>
                           <th> <?= cclang('order_shipping_first_name') ?></th>
                           <th> <?= cclang('order_shipping_last_name') ?></th>
                           <th> <?= cclang('order_shipping_company') ?></th>
                           <th> <?= cclang('order_shipping_address_1') ?></th>
                           <th> <?= cclang('order_shipping_address_2') ?></th>
                           <th> <?= cclang('order_shipping_city') ?></th>
                           <th> <?= cclang('order_shipping_state') ?></th>
                           <th> <?= cclang('order_shipping_postcode') ?></th>
                           <th> <?= cclang('order_shipping_country') ?></th>
                           <th>Action</th>                        </tr>
                     </thead>
                     <tbody id="tbody_api_orders">
                     <?php foreach($api_orderss as $api_orders): ?>
                        <tr>
                                                       <td width="5">
                              <input type="checkbox" class="flat-red check" name="id[]" value="<?= $api_orders->id; ?>">
                           </td>
                                                       
                           <td><?= _ent($api_orders->id); ?></td> 
                           <td><?= _ent($api_orders->user_id); ?></td> 
                           <td><?= _ent($api_orders->order_number); ?></td> 
                           <td><?= _ent($api_orders->order_parent_id); ?></td> 
                           <td><?= _ent($api_orders->order_status); ?></td> 
                           <td><?= _ent($api_orders->order_currency); ?></td> 
                           <td><?= _ent($api_orders->order_version); ?></td> 
                           <td><?= _ent($api_orders->order_payment_method); ?></td> 
                           <td><?= _ent($api_orders->order_payment_method_title); ?></td> 
                           <td><?= _ent($api_orders->order_date_created); ?></td> 
                           <td><?= _ent($api_orders->order_date_modified); ?></td> 
                           <td><?= _ent($api_orders->order_timestamp_created); ?></td> 
                           <td><?= _ent($api_orders->order_timestamp_modified); ?></td> 
                           <td><?= _ent($api_orders->order_discount_total); ?></td> 
                           <td><?= _ent($api_orders->order_discount_tax); ?></td> 
                           <td><?= _ent($api_orders->order_shipping_total); ?></td> 
                           <td><?= _ent($api_orders->order_shipping_tax); ?></td> 
                           <td><?= _ent($api_orders->order_total_tax); ?></td> 
                           <td><?= _ent($api_orders->order_customer_id); ?></td> 
                           <td><?= _ent($api_orders->order_billing_first_name); ?></td> 
                           <td><?= _ent($api_orders->order_billing_last_name); ?></td> 
                           <td><?= _ent($api_orders->order_billing_company); ?></td> 
                           <td><?= _ent($api_orders->order_billing_address_1); ?></td> 
                           <td><?= _ent($api_orders->order_billing_city); ?></td> 
                           <td><?= _ent($api_orders->order_billing_state); ?></td> 
                           <td><?= _ent($api_orders->order_billing_postcode); ?></td> 
                           <td><?= _ent($api_orders->order_billing_country); ?></td> 
                           <td><?= _ent($api_orders->order_billing_email); ?></td> 
                           <td><?= _ent($api_orders->order_billing_phone); ?></td> 
                           <td><?= _ent($api_orders->order_shipping_first_name); ?></td> 
                           <td><?= _ent($api_orders->order_shipping_last_name); ?></td> 
                           <td><?= _ent($api_orders->order_shipping_company); ?></td> 
                           <td><?= _ent($api_orders->order_shipping_address_1); ?></td> 
                           <td><?= _ent($api_orders->order_shipping_address_2); ?></td> 
                           <td><?= _ent($api_orders->order_shipping_city); ?></td> 
                           <td><?= _ent($api_orders->order_shipping_state); ?></td> 
                           <td><?= _ent($api_orders->order_shipping_postcode); ?></td> 
                           <td><?= _ent($api_orders->order_shipping_country); ?></td> 
                           <td width="200">
                            
                                                              <?php is_allowed('api_orders_view', function() use ($api_orders){?>
                                 <a href="<?= site_url('administrator/api_orders/single_pdf/' .$api_orders->id); ?>" class="label-default"><i class="fa fa-file-pdf-o"></i> <?= cclang('PDF') ?>
                              <a href="<?= site_url('administrator/api_orders/view/' . $api_orders->id); ?>" class="label-default"><i class="fa fa-newspaper-o"></i> <?= cclang('view_button'); ?>
                              <?php }) ?>
                              <?php is_allowed('api_orders_update', function() use ($api_orders){?>
                              <a href="<?= site_url('administrator/api_orders/edit/' . $api_orders->id); ?>" class="label-default"><i class="fa fa-edit "></i> <?= cclang('update_button'); ?></a>
                              <?php }) ?>
                              <?php is_allowed('api_orders_delete', function() use ($api_orders){?>
                              <a href="javascript:void(0);" data-href="<?= site_url('administrator/api_orders/delete/' . $api_orders->id); ?>" class="label-default remove-data"><i class="fa fa-close"></i> <?= cclang('remove_button'); ?></a>
                               <?php }) ?>

                           </td>                        </tr>
                      <?php endforeach; ?>
                      <?php if ($api_orders_counts == 0) :?>
                         <tr>
                           <td colspan="100">
                           Api Orders data is not available
                           </td>
                         </tr>
                      <?php endif; ?>
                     </tbody>
                  </table>
                  </div>
               </div>
               <hr>
               <!-- /.widget-user -->
               <div class="row">
                  <div class="col-md-8">
                     <div class="col-sm-2 padd-left-0 " >
                        <select type="text" class="form-control chosen chosen-select" name="bulk" id="bulk" placeholder="Site Email" >
                           <option value="">Bulk</option>
                                                     <option value="delete">Delete</option>
                                                  </select>
                     </div>
                     <div class="col-sm-2 padd-left-0 ">
                        <button type="button" class="btn btn-flat" name="apply" id="apply" title="<?= cclang('apply_bulk_action'); ?>"><?= cclang('apply_button'); ?></button>
                     </div>
                     <div class="col-sm-3 padd-left-0  " >
                        <input type="text" class="form-control" name="q" id="filter" placeholder="<?= cclang('filter'); ?>" value="<?= $this->input->get('q'); ?>">
                     </div>
                     <div class="col-sm-3 padd-left-0 " >
                        <select type="text" class="form-control chosen chosen-select" name="f" id="field" >
                           <option value=""><?= cclang('all'); ?></option>
                            <option <?= $this->input->get('f') == 'id' ? 'selected' :''; ?> value="id">Id</option>
                           <option <?= $this->input->get('f') == 'user_id' ? 'selected' :''; ?> value="user_id">User Id</option>
                           <option <?= $this->input->get('f') == 'order_number' ? 'selected' :''; ?> value="order_number">Order Number</option>
                           <option <?= $this->input->get('f') == 'order_parent_id' ? 'selected' :''; ?> value="order_parent_id">Order Parent Id</option>
                           <option <?= $this->input->get('f') == 'order_status' ? 'selected' :''; ?> value="order_status">Order Status</option>
                           <option <?= $this->input->get('f') == 'order_currency' ? 'selected' :''; ?> value="order_currency">Order Currency</option>
                           <option <?= $this->input->get('f') == 'order_version' ? 'selected' :''; ?> value="order_version">Order Version</option>
                           <option <?= $this->input->get('f') == 'order_payment_method' ? 'selected' :''; ?> value="order_payment_method">Order Payment Method</option>
                           <option <?= $this->input->get('f') == 'order_payment_method_title' ? 'selected' :''; ?> value="order_payment_method_title">Order Payment Method Title</option>
                           <option <?= $this->input->get('f') == 'order_date_created' ? 'selected' :''; ?> value="order_date_created">Order Date Created</option>
                           <option <?= $this->input->get('f') == 'order_date_modified' ? 'selected' :''; ?> value="order_date_modified">Order Date Modified</option>
                           <option <?= $this->input->get('f') == 'order_timestamp_created' ? 'selected' :''; ?> value="order_timestamp_created">Order Timestamp Created</option>
                           <option <?= $this->input->get('f') == 'order_timestamp_modified' ? 'selected' :''; ?> value="order_timestamp_modified">Order Timestamp Modified</option>
                           <option <?= $this->input->get('f') == 'order_discount_total' ? 'selected' :''; ?> value="order_discount_total">Order Discount Total</option>
                           <option <?= $this->input->get('f') == 'order_discount_tax' ? 'selected' :''; ?> value="order_discount_tax">Order Discount Tax</option>
                           <option <?= $this->input->get('f') == 'order_shipping_total' ? 'selected' :''; ?> value="order_shipping_total">Order Shipping Total</option>
                           <option <?= $this->input->get('f') == 'order_shipping_tax' ? 'selected' :''; ?> value="order_shipping_tax">Order Shipping Tax</option>
                           <option <?= $this->input->get('f') == 'order_total_tax' ? 'selected' :''; ?> value="order_total_tax">Order Total Tax</option>
                           <option <?= $this->input->get('f') == 'order_customer_id' ? 'selected' :''; ?> value="order_customer_id">Order Customer Id</option>
                           <option <?= $this->input->get('f') == 'order_billing_first_name' ? 'selected' :''; ?> value="order_billing_first_name">Order Billing First Name</option>
                           <option <?= $this->input->get('f') == 'order_billing_last_name' ? 'selected' :''; ?> value="order_billing_last_name">Order Billing Last Name</option>
                           <option <?= $this->input->get('f') == 'order_billing_company' ? 'selected' :''; ?> value="order_billing_company">Order Billing Company</option>
                           <option <?= $this->input->get('f') == 'order_billing_address_1' ? 'selected' :''; ?> value="order_billing_address_1">Order Billing Address 1</option>
                           <option <?= $this->input->get('f') == 'order_billing_city' ? 'selected' :''; ?> value="order_billing_city">Order Billing City</option>
                           <option <?= $this->input->get('f') == 'order_billing_state' ? 'selected' :''; ?> value="order_billing_state">Order Billing State</option>
                           <option <?= $this->input->get('f') == 'order_billing_postcode' ? 'selected' :''; ?> value="order_billing_postcode">Order Billing Postcode</option>
                           <option <?= $this->input->get('f') == 'order_billing_country' ? 'selected' :''; ?> value="order_billing_country">Order Billing Country</option>
                           <option <?= $this->input->get('f') == 'order_billing_email' ? 'selected' :''; ?> value="order_billing_email">Order Billing Email</option>
                           <option <?= $this->input->get('f') == 'order_billing_phone' ? 'selected' :''; ?> value="order_billing_phone">Order Billing Phone</option>
                           <option <?= $this->input->get('f') == 'order_shipping_first_name' ? 'selected' :''; ?> value="order_shipping_first_name">Order Shipping First Name</option>
                           <option <?= $this->input->get('f') == 'order_shipping_last_name' ? 'selected' :''; ?> value="order_shipping_last_name">Order Shipping Last Name</option>
                           <option <?= $this->input->get('f') == 'order_shipping_company' ? 'selected' :''; ?> value="order_shipping_company">Order Shipping Company</option>
                           <option <?= $this->input->get('f') == 'order_shipping_address_1' ? 'selected' :''; ?> value="order_shipping_address_1">Order Shipping Address 1</option>
                           <option <?= $this->input->get('f') == 'order_shipping_address_2' ? 'selected' :''; ?> value="order_shipping_address_2">Order Shipping Address 2</option>
                           <option <?= $this->input->get('f') == 'order_shipping_city' ? 'selected' :''; ?> value="order_shipping_city">Order Shipping City</option>
                           <option <?= $this->input->get('f') == 'order_shipping_state' ? 'selected' :''; ?> value="order_shipping_state">Order Shipping State</option>
                           <option <?= $this->input->get('f') == 'order_shipping_postcode' ? 'selected' :''; ?> value="order_shipping_postcode">Order Shipping Postcode</option>
                           <option <?= $this->input->get('f') == 'order_shipping_country' ? 'selected' :''; ?> value="order_shipping_country">Order Shipping Country</option>
                          </select>
                     </div>
                     <div class="col-sm-1 padd-left-0 ">
                        <button type="submit" class="btn btn-flat" name="sbtn" id="sbtn" value="Apply" title="<?= cclang('filter_search'); ?>">
                        Filter
                        </button>
                     </div>
                     <div class="col-sm-1 padd-left-0 ">
                        <a class="btn btn-default btn-flat" name="reset" id="reset" value="Apply" href="<?= base_url('administrator/api_orders');?>" title="<?= cclang('reset_filter'); ?>">
                        <i class="fa fa-undo"></i>
                        </a>
                     </div>
                  </div>
                  </form>                  <div class="col-md-4">
                     <div class="dataTables_paginate paging_simple_numbers pull-right" id="example2_paginate" >
                        <?= $pagination; ?>
                     </div>
                  </div>
               </div>
            </div>
            <!--/box body -->
         </div>
         <!--/box -->
      </div>
   </div>
</section>
<!-- /.content -->

<!-- Page script -->
<script>
  $(document).ready(function(){
   
    $('.remove-data').click(function(){

      var url = $(this).attr('data-href');

      swal({
          title: "<?= cclang('are_you_sure'); ?>",
          text: "<?= cclang('data_to_be_deleted_can_not_be_restored'); ?>",
          type: "warning",
          showCancelButton: true,
          confirmButtonColor: "#DD6B55",
          confirmButtonText: "<?= cclang('yes_delete_it'); ?>",
          cancelButtonText: "<?= cclang('no_cancel_plx'); ?>",
          closeOnConfirm: true,
          closeOnCancel: true
        },
        function(isConfirm){
          if (isConfirm) {
            document.location.href = url;            
          }
        });

      return false;
    });


    $('#apply').click(function(){

      var bulk = $('#bulk');
      var serialize_bulk = $('#form_api_orders').serialize();

      if (bulk.val() == 'delete') {
         swal({
            title: "<?= cclang('are_you_sure'); ?>",
            text: "<?= cclang('data_to_be_deleted_can_not_be_restored'); ?>",
            type: "warning",
            showCancelButton: true,
            confirmButtonColor: "#DD6B55",
            confirmButtonText: "<?= cclang('yes_delete_it'); ?>",
            cancelButtonText: "<?= cclang('no_cancel_plx'); ?>",
            closeOnConfirm: true,
            closeOnCancel: true
          },
          function(isConfirm){
            if (isConfirm) {
               document.location.href = BASE_URL + '/administrator/api_orders/delete?' + serialize_bulk;      
            }
          });

        return false;

      } else if(bulk.val() == '')  {
          swal({
            title: "Upss",
            text: "<?= cclang('please_choose_bulk_action_first'); ?>",
            type: "warning",
            showCancelButton: false,
            confirmButtonColor: "#DD6B55",
            confirmButtonText: "Okay!",
            closeOnConfirm: true,
            closeOnCancel: true
          });

        return false;
      }

      return false;

    });/*end appliy click*/


    //check all
    var checkAll = $('#check_all');
    var checkboxes = $('input.check');

    checkAll.on('ifChecked ifUnchecked', function(event) {   
        if (event.type == 'ifChecked') {
            checkboxes.iCheck('check');
        } else {
            checkboxes.iCheck('uncheck');
        }
    });

    checkboxes.on('ifChanged', function(event){
        if(checkboxes.filter(':checked').length == checkboxes.length) {
            checkAll.prop('checked', 'checked');
        } else {
            checkAll.removeProp('checked');
        }
        checkAll.iCheck('update');
    });

  }); /*end doc ready*/
</script>